### ISSUE TITLE
Sandbox component wasn't found

### ISSUE THREAD

**Issue by klauskpm** [SoCreate/angular-playground#100]
### Versions
```
"angular-playground": "^3.4.0",
```

```
Your global Angular CLI version (1.7.2) is greater than your local
version (1.7.1). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.7.1 (e)
Node: 8.9.4
OS: win32 x64
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.1
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack-dev-server: 2.11.1
webpack: 3.11.0
```

### Repro steps

* Clone this project : https://github.com/klauskpm/playground-test
* Install all dependencies with `yarn` or `npm`
* Run the project with `npm run playground`

### Observed Behavior
```
The system runs without an apparent problem, but it doesn't find the sandbox component.
```
![image](https://user-images.githubusercontent.com/690945/37175400-2e3b2bac-22f8-11e8-880d-40ee9585c607.png)

### Desired Behavior
```
I expect it to find the sandbox component.
```

### Any other details that may be useful (optional)
The project was generated with angular-cli, and then ejected through `ng eject`.
We changed some basic configurations, and moved the TypeScript configuration files to `/src/config`.
I've tried to follow the webpack setup guide.
The project is running on Windows 10.

**Comment by mgmarlow** [comment]
Ah, so part of the issue here is some bad error reporting code on our end that is fixed in a branch I am currently working on. You need to pass in the `--no-serve` flag since you are not running the Angular CLI behind the scenes.

In other words, the sandboxes aren't being compiled since the Playground CLI is breaking due to looking for an Angular CLI appName for Playground and not being able to find it.

Here's what the output looks like when running it with my dev branch:

![image](https://user-images.githubusercontent.com/3778552/37315312-4aa2ad30-2616-11e8-83f8-88ddb462a211.png)

In addition to this, it looks like the sandboxes aren't being picked up as part of the webpack compilation, so I am currently looking into that issue as well.

**Comment by mgmarlow** [comment]
OK, so after digging into the issues I had after resolving the above (with the latest version of playground, which will be releasing in the next few days), I think you have an issue with the nested `tsconfig.app.json` files. The Angular Webpack plugin doesn't play nicely when the location of the `tsconfig` isn't at the root of the source directory. e.g. your config lives in `./src/config/tsconfig.app.json`, whereas the source lives in `./src/shared/tabs/`.

Here's an example ejected app I got working with playground: https://github.com/mgmarlow/ejected-playground

The only item I changed in the webpack configuration was the entrypoint (which you could replicate using webpack merge):
```
  "entry": {
    "main": [
      "./src\\main.playground.ts"
    ],
    ...
```

My script for calling playground was appended with `--no-serve`:
```
# package.json
{
  ...
  "scripts": {
    ...
    "playground": "concurrently \"npm run playground:run\" \"npm run playground:serve\"",
    "playground:run": "angular-playground --no-serve",
    "playground:serve": "webpack-dev-server --port=4201",
    ...
```

I hope this helps. If you run into more issues running Playground please open a new ticket so we can keep the errors isolated.

I'll update the Playground docs with this information as well, as the non-CLI walk-through appears out of date.
