### ISSUE TITLE
Search doesn't work: this.filter.valueChanges.debounceTime is not a function

### ISSUE THREAD

**Issue by akinorew** [SoCreate/angular-playground#110]
### Versions
```
angular-playground version 4.0.0
```

```
Output from: `ng --version`.
Angular CLI: 1.7.3
Node: 9.0.0
OS: darwin x64
Angular: 5.2.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

@angular/cdk: 5.2.4
@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0
```

### Repro steps
* Run playground
* You can see the error immediately in console

### Observed Behavior
```
Search for components doesn't work
```

### Desired Behavior
```
Search works
```

![screen shot 2018-04-16 at 14 33 32](https://user-images.githubusercontent.com/3313388/38809432-c276a41e-4183-11e8-82ba-96d6e00eae53.png)

### Any other details that may be useful (optional)
To fix it in app.component.js
import { Observable } from 'rxjs/Rx';

**Comment by lurock** [comment]
Can you post a link to a project on GitHub with this setup?

**Comment by akinorew** [comment]
@lurock I tried to reproduce this issue with the small app that had the same dependencies and versions as the app I have, that has this issue. I couldn't reproduce it. It seems like something flaky happening.

**Comment by akinorew** [comment]
@lurock It seems it was the tsconfig configuration:

"paths": {
    "*": [ "node_modules/*", "source/*", "styleguide/*"]
}

and this issue is related to https://github.com/ReactiveX/rxjs/issues/2984

**Comment by lurock** [comment]
It sounds like you have resolved the issue.  Closing issue, please feel free to comment if your are still having an issue.
