### ISSUE TITLE
[feature request] Using feature module for imports

### ISSUE THREAD

**Issue by e11en** [SoCreate/angular-playground#111]
So I just started using Playground and I really like it so far but I'm missing the ability to import a feature module so I don't have to redefine all the imports from my module. When I do just import my feature module I get the error saying the component is declared in two modules `Error: Type LoginComponent is part of the declarations of 2 modules: LoginModule and DynamicModule!`

Hope this is possible! Thanks in advance.

My setup:
```
"angular-playground": "^4.0.0"
Angular CLI: 1.6.5
Node: 8.9.1
OS: win32 x64
Angular: 5.2.6
```

**Comment by lurock** [comment]
If the LoginComponent is already declared in the LoginModule you need to set declareComponent to false.  See the docs here http://www.angularplayground.it/docs/api/sandbox about the declareComponent setting.
