### ISSUE TITLE
What would be the config in angular.json for the angular v6?

### ISSUE THREAD

**Issue by goldenbearkin** [SoCreate/angular-playground#113]
angular v6 no longer has the angular-cli.json, it moves the config to angular.json instead. Could anybody figure out the right way of applying the config in the new angular.json ? Many thanks!!!

**Comment by arroyocode** [comment]
@goldenbearkin We will be upgrading playground shortly after angular v6 is officially released. Stay tuned.

**Comment by DanWahlin** [comment]
Thanks @arroyocode. Interested in this as well. 

I've tried to upgrade things to what I'm guessing it'll be (`ng upgrade @angular/cli` refactored the angular.json file of course),  but when I do `npm run playround` I'm getting `[ng serve]: Unknown option: '-n'`. Hoping I just need to do a small tweak. Thanks!

**Comment by Buttars** [comment]
@arroyocode Do you have a rough timeframe so I know when I should check back?

**Comment by JustinCouto** [comment]
@Buttars we are in the process of figuring out the best way to support the changes in Angular 6 in Playground.  We use Playground as a part of our daily development, so it is critical for us to get it updated as soon as possible.  Once we finish determining the plan we should be able to post an ETA.  Our team has a busy week a head of them and we likely wont have an update until the week of the 14th.  We are actively working on it though and if it is done sooner than that we will get it released.

**Comment by Buttars** [comment]
@JustinCouto You're the man! Thank you for your contributions to the opensource community.

**Comment by sulco** [comment]
Hey @JustinCouto, if you could use some additional hands on this, I'd be up to help. 
Playground really shaved some substantial hours in my recent development, so I would gladly give back.

**Comment by akinorew** [comment]
To fix this issue, there has to be change in serve-angular-cli.js

`function configureArguments(config) {
    let args = [config.angularCliPath, 'serve', **'--no-progress'**];
    args.push(`--port=${config.angularCliPort}`);
    if (config.angularAppName) {
        args.push(`**--project**=${config.angularAppName}`);
    }
    else {
        throw new Error('Please provide Playground\'s appName in your angular-playground.json file.');
    }
    if (config.angularCliEnv) {
        args.push(`-e=${config.angularCliEnv}`);
    }
    if (config.angularCliAdditionalArgs) {
        args = args.concat(config.angularCliAdditionalArgs);
    }
    return args;
}`

**Comment by JustinCouto** [comment]
@sulco thank you so much for the offer.  Currently, we are evaluating the best way to do the upgrade and planning for the future direction.  We hope to have something out by the end of this week.  Once we have the plan figured out, we might take you up on your offer.  We do appreciate it and are happy to hear Playground has been a big help to you.  It has certainly changed the way we do things here.

**Comment by daiky00** [comment]
@JustinCouto I need this ASAP please update us when this is done

**Comment by LPCmedia** [comment]
I was able to fork and do the upgrade using rxjs-compat. I can probably remove it shortly but at least I am unblocked by this from my end. 

see comments here: 
https://github.com/SoCreate/angular-playground/pull/118/files

**Comment by isaacplmann** [comment]
Thanks @LPCmedia !  Your fork works for me too.

**Comment by lurock** [comment]
Hey All, I published a new version that works with Angular 6 and also update the [docs site](http://www.angularplayground.it).  Check the [change log](https://github.com/SoCreate/angular-playground/blob/master/packages/angular-playground/CHANGELOG.md) to see what you need to change in your project after you npm install the new version of angular-playground.

**Comment by DanWahlin** [comment]
Thanks!
