### ISSUE TITLE
Error in console log in the hybrid setup

### ISSUE THREAD

**Issue by akinorew** [SoCreate/angular-playground#115]
### Versions
```
angular-playground version 4.0.0
```

```
Angular CLI: 1.7.3
Node: 8.0.0
OS: darwin x64
Angular: 5.2.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

@angular/cdk: 5.2.4
@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0
```

### Repro steps
Run playground

### Observed Behavior
```
Unhandled Promise rejection: No component factory found for AppComponent. Did you add it to @NgModule.entryComponents? ; Zone: <root> ; Task: Promise.then ; Value: Error: No component factory found for AppComponent. Did you add it to @NgModule.entryComponents?
```

![screen shot 2018-05-08 at 10 20 59](https://user-images.githubusercontent.com/3313388/39746059-88ce1436-52a9-11e8-821e-d5b86aed42ca.png)

### Example app:
https://github.com/akinorew/test-playground

**Comment by arroyocode** [comment]
Good day @akinorew. Thank you for your interest in Playground and the sample repository. I'm afraid we're not able to provide support for Angular JS/Angular hybrid Playground projects as our internal focus is specifically Angular. We apologize but this is not something we can address for you.
