### ISSUE TITLE
App is hosted as `ap-root` instead of `app-root`

### ISSUE THREAD

**Issue by ciesielskico** [SoCreate/angular-playground#116]
### Versions
```
4.0.1
```

```
Angular CLI: 1.7.0
Node: 9.11.1
OS: win32 x64
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 6.0.0-beta.4
@angular/cli: 1.7.0
@angular/material: 6.0.0-beta.4
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.4.2
webpack-bundle-analyzer: 2.11.0
webpack: 3.11.0
```

### Repro steps

I've setup a simple angular-playground project to test a single component and I get this:

![image](https://user-images.githubusercontent.com/17651898/39865560-93be377c-544d-11e8-8a1e-c1be78038998.png)

> main.playground.ts
```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { PlaygroundModule } from 'angular-playground';
import './rxjs.imports';

PlaygroundModule.configure({
  selector: 'app-root',
  overlay: false,
  modules: []
});

platformBrowserDynamic().bootstrapModule(PlaygroundModule);
```

>angular-playground.json
```
{
  "sourceRoot": "./src",
  "angularCli": {
    "appName": "playground"
  }
}
```

### Observed Behavior
`ap-root`  appears in Chrome Devtools.

### Desired Behavior
`app-root` should appear in Chrome Devtools

I have looked for `ap-root` in the entire project and could not find anything.

**Comment by arroyocode** [comment]
@ciesielskico The `ap-` naming convention is intentional as is relates to Angular Playground and is used in other Component selector values within the project (i.e.: `ap-root`, `ap-pin`, `ap-logo`, `ap-drawer`, `ap-scenario`) so I'm afraid we won't be making this change. We appreciate your submission!
