### ISSUE TITLE
Stackblitz integration

### ISSUE THREAD

**Issue by gnomeontherun** [SoCreate/angular-playground#117]
It would be very useful to be able to somehow ship a sandboxed component to Stackblitz. This could be done through the [POST API](https://stackblitz.com/docs#post-api) or [JavaScript API openProject](https://stackblitz.com/docs#sdk-openproject-project-opts).

From a user's perspective, having a button to 'export to stackblitz' would be the ideal scenario, where the client could then upload the current assets into a new stackblitz project.

**Comment by arroyocode** [comment]
Good day @gnomeontherun, we have discussed this request internally and have come to the conclusion that this is not something we're planning to do primarily for lack of internal development need. We do see the value in this for others outside our organization, thus, we would be open to reviewing a PR should someone in the community be willing to take on the task.
