### ISSUE TITLE
Nrwl/NX Compatibility

### ISSUE THREAD

**Issue by kpaxton** [SoCreate/angular-playground#119]
### Versions
```
4.0.1
```

```
Cli: 1.7.4
Node: 8.11.1
Angular: 5.2.9
Typescript: 2.7.1
```

### Repro steps
In an NX Workspace I have a single App with multiple libs. 
I have followed the instructions for creating a playground and have a ```main.playground.ts``` in the single app. I have added an app names ```playground``` in the ```.angular-cli.json``` and it's basically a duplicate of the root app configuration. I have a ```sandboxes``` folder for sandboxes for the libs to work, but in app components have their sandbox next to the component. 

### Observed Behavior
When building the playground everything works fine. 
When building the app, I get this:
```
ERROR in ./apps/app/src/main.playground.ts
Module not found: Error: Can't resolve '...playground.module.d.ngfactory' in '...apps/app/src'
```

### Desired Behavior
Obviously I would like to build my app separately from the playground in an NX Workspace structure. 

### Any other details that may be useful (optional)
I have tried to create a separate ```tsconfig.app.playground.json``` to have an exclude for ```main.playground.ts``` and ```*.sandbox.ts``` but it doesn't seem to change anything. 

Is there an example of usage within an NX Workspace that I can follow?

**Comment by arroyocode** [comment]
Afternoon @kpaxton. I'm afraid we don't have a usage example within an NX Workspace as we don't use NX internally. Unfortunately, this is not something on our roadmap currently. We appreciate your request and use of Playground.
