### ISSUE TITLE
Add HMR (Hot Module Reloading) support

### ISSUE THREAD

**Issue by bengry** [SoCreate/angular-playground#121]
### Versions
```
angular-playground: 5.0.1
angular: 6.0.3
```

### Repro steps

1. Create new Angular CLI project (`npx @angular/cli new sample-repo`)
2. Follow [directions here to add HMR](https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/configure-hmr.md).
3. Run `npm run angular-playground --ng-cli-args --hmr --env=hmr`.
4. Open browser and navigate to a sandbox.
5. Modify a Sandbox/Component.

### Observed Behavior
Browser refreshes

### Desired Behavior
Browser does not refresh, and change are applied in-place.

**Comment by arroyocode** [comment]
Hiya @bengry . Thank you for your interest in Angular Playground. We don't have a need for HMR internally and currently have no plans to integrate such a feature.
