### ISSUE TITLE
Custom <ap-root> component and dynamic scenario

### ISSUE THREAD

**Issue by GrandSchtroumpf** [SoCreate/angular-playground#125]
### Versions
angular-playground
```
5.0.1
```
@angular/cli
```
6.0.7
```

I would like to use Angular Playground to build a visual component builder (like [Ionic Creator](https://creator.ionic.io/). for that I need to programmatically add or remove sandboxOf, and manipulate the scenarios.

### Manipluate sandboxOf
If I understand right your app, I think we should be able to fill the `sandboxes.ts` file through some API. Something like `addSandbox(sandbox: SandboxBuilder)` and `removeSandbox(description: string)`.

### Manipulate Scenarios
To manipulate the scenarios the best would be to have a custom component to replace the `<ap-root>`. It would also help to manage incoming message for embedded playground.

**Comment by arroyocode** [comment]
Hello @GrandSchtroumpf. Could we trouble you to provide more detail about what is needed? We reviewed the issue internally and feel we need more info to be able to provide a more accurate response.

**Comment by GrandSchtroumpf** [comment]
Of course. The problem is that the `angular-playground/core/src/shared/sandboxes.ts` file is only filled by the cli. I would like an API to fill the file dynamically through a web app. Like that we can have user building the component from a visual editor and show the result dynamically. That's why I was thinking about two functions to fill and remove the components inside `sandboxes.ts`file.

My other issue is that I would like my users to have some feedbacks when they hover the component displayed. So I would like to be able to plug my own component around the `<ap-scenario>` instead of `<ap-root>`. It can be achieved through interfaces or `ViewChild` maybe...

Sorry if I don't provide some technical solutions to my issues ...

**Comment by arroyocode** [comment]
Hiya @GrandSchtroumpf . Thank you for your interest in Angular Playground. We don't envision building any form of a visual component builder in the future.
