### ISSUE TITLE
Add helping onramp for new developers using playground

### ISSUE THREAD

**Issue by StephenFluin** [SoCreate/angular-playground#139]
### Versions
```
angular-playground@5.1.3
```

### Repro steps
* yarn playground
* visit localhost:4201

### Observed Behavior
![image](https://user-images.githubusercontent.com/165056/44595003-9b6a0500-a77c-11e8-9f37-02c8c641c62c.png)

### Desired Behavior
Many developers will discover playground with `ng add`, it would be helpful if upon install you print out some getting started instructions, and if the user doesn't have any sandboxed components when visiting localhost:4201, you should provide a link showing them how to get started creating them.

**Comment by lurock** [comment]
Great feedback!  Thank you.  We are going to add a link to the docs for creating sandboxes when a user does not have any created.
