### ISSUE TITLE
TypeError: __webpack_require__.e is not a function

### ISSUE THREAD

**Issue by timstoddard** [SoCreate/angular-playground#142]
### Versions

```
angular-playground v5.1.3
```

```
Angular CLI: 6.1.5
Node: 10.8.0
OS: win32 x64
Angular: 6.1.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cli                      6.1.5
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2
```

### Repro steps

1. Create a new angular project (via `ng new`).
2. Make a typescript error in the code somewhere.
3. Run `ng serve`, and wait until you see a compilation error.
5. Fix the typescript error.
6. Go back to the playground page; on reload, it should produce this error.

### Observed Behavior

```
ERROR TypeError: __webpack_require__.e is not a function
    at getSandbox (sandboxes.js:8)
    at Function.push../node_modules/ng-play/dist/build/src/shared/sandbox-loader.js.SandboxLoader.loadSandbox (sandbox-loader.js:6)
    at ScenarioComponent.push../node_modules/ng-play/dist/build/src/scenario/scenario.component.js.ScenarioComponent.bootstrapSandbox (scenario.component.js:51)
    at ScenarioComponent.push../node_modules/ng-play/dist/build/src/scenario/scenario.component.js.ScenarioComponent.ngOnChanges (scenario.component.js:29)
    at checkAndUpdateDirectiveInline (core.js:9246)
    at checkAndUpdateNodeInline (core.js:10514)
    at checkAndUpdateNode (core.js:10476)
    at debugCheckAndUpdateNode (core.js:11109)
    at debugCheckDirectivesFn (core.js:11069)
    at Object.eval [as updateDirectives] (AppComponent.html:90)
```

### Desired Behavior

```
Playground should load sandboxes without errors.
```

**Comment by timstoddard** [comment]
submitted a bug report against the angular-cli repo
https://github.com/angular/angular-cli/issues/12062

**Comment by Kr0san89** [comment]
Hello, @timstoddard have a similar Problem. I downgraded playground to Version 5.0.0 and it works again.

**Comment by timstoddard** [comment]
@Kr0san89 I updated the repro steps since I found a deterministic way to reproduce the error. Was that similar to the steps you took when you ran into the error?

**Comment by Kr0san89** [comment]
@timstoddard 
I had an already existing project with no erros. (Angular 6)
I just added playground with ng add as Descriped on the page
-> had the Failure.

Since i use playground on another project it -> i downgraded to same version

**Comment by centigrade-julian-lang** [comment]
I had the same error, but for me it was enough to stop the running `angular-playground` process and restart it via `npx angular-playground`

**Comment by arroyocode** [comment]
Issue related to dynamically loading modules (see [#9825](https://github.com/angular/angular-cli/issues/9825#issuecomment-388728694)).

Re-creating sample project as an Angular 8 CLI project with Angular Playground >= 6:

```
angular-playground v6.0.1
```

```
Angular CLI: 8.1.2
Node: 10.16.0
OS: win32 x64
Angular: 8.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.2
@angular-devkit/build-angular     0.801.2
@angular-devkit/build-optimizer   0.801.2
@angular-devkit/build-webpack     0.801.2
@angular-devkit/core              8.1.2
@angular-devkit/schematics        8.1.2
@ngtools/webpack                  8.1.2
@schematics/angular               8.1.2
@schematics/update                0.801.2
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2
```

now produces different behavior (`Failed to load resource: the server responded with a status of 404 (Not Found)`) when running `ng serve` or `npm run playground` while an error is present. Fixing the error and reloading playground no longer produces the `TypeError: __webpack_require__.e is not a function` issue.
