### ISSUE TITLE
How to sandbox components that are part of a library in the workspace of cli?

### ISSUE THREAD

**Issue by brugsel** [SoCreate/angular-playground#143]
### Versions
```
angular-playground version 5.1.3
```

```
<!-   _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.1.4
Node: 8.9.4
OS: darwin x64
Angular: 6.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.7.4
@angular/cli                      6.1.4
@ngtools/webpack                  6.0.8
@schematics/angular               0.7.4
@schematics/update                0.7.4
rxjs                              6.2.1
typescript                        2.9.2
webpack                           4.8.3
```

### Repro steps
* Install a new workspace following the default steps of Angular CLI v6
* Install Angular Playground 
* Add a Library project to the cli workspace
* Add a component and sandbox to the library project

### Observed Behavior
```
Components and sandboxes in the library project are not found by Angular Playground. When the sandbox is moved to the main project where Angular Playground is added to, the sandbox is found. But still the component that is sandboxed is not. 

Only when the component and the sandbox are part of the main project, the sandbox is working with the component.
```

### Desired Behavior
```
What I expect is that sandboxes and components in library projects in the same workspace are discovered. Especially when the main application is using the library in the workspace. 
```

### Any other details that may be useful (optional)

**Comment by timstoddard** [comment]
Hello @brugsel, we have reviewed this issue and have determined that we will support this feature. We will work on it sometime in the near future; if you would like to see this issue resolved sooner, feel free to submit a PR with the fix!

**Comment by allanbond** [comment]
You can do this by updating the tsconfig.app.json inside the playground project.

`  "include": ["**/*.ts", "../my-controls-lib/src/**/*.sandbox.ts", "../my-other-lib/src/**/*.sandbox.ts"]`

**Comment by timstoddard** [comment]
@brugsel angular-playground does not have that feature yet but we plan to add support for libraries sometime in the future. If you would like to create a PR to see that feature added sooner, we welcome you to submit one!

**Comment by frederikprijck** [comment]
You can see a working example on combining nx with angular-playground here: https://github.com/frederikprijck/angular-playground-nx.

Basicly what you need to do is:

- npm i angular-playground -D
- ng g app playground
- update the playground app's main.ts file:
```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { PlaygroundModule } from 'angular-playground';

PlaygroundModule
  .configure({
    selector: 'playground-root',
    overlay: false,
    modules: []
  });
platformBrowserDynamic().bootstrapModule(PlaygroundModule);
```
- add `"../../libs/**/*.sandbox.ts"` to the includes in playground's tsconfig.app.json
- add an angular-playground.json file to the root of your project:
```
{
  "sourceRoot": "./libs",
  "angularCli": {
    "appName": "playground"
  }
}
```

> Note: Do not use `ng add angular-playground`, if you did you'll need to remove the `src` directory it created and remove the app in `angular.json`.

Credits to @jschwarty for helping me getting this running in nx.

**Comment by rootical** [comment]
Thanks, @frederikprijck. 

Any news on when the official component libraries support could be added?
