### ISSUE TITLE
Reloading page navigates away from the component and back to the "home" screen

### ISSUE THREAD

**Issue by jornare** [SoCreate/angular-playground#146]
### Versions
```
angular-playground version 5.1.3

```

```
Angular CLI: 6.2.4
Node: 8.12.0
OS: win32 x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.8.4
@angular-devkit/build-angular      0.8.4
@angular-devkit/build-ng-packagr   0.8.4
@angular-devkit/build-optimizer    0.8.4
@angular-devkit/build-webpack      0.8.4
@angular-devkit/core               0.8.4
@angular-devkit/schematics         0.8.4
@angular/cdk                       6.4.7
@angular/cli                       6.2.4
@angular/material                  6.4.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.2.4
@schematics/angular                0.8.4
@schematics/update                 0.8.4
ng-packagr                         4.2.0
rxjs                               6.3.3
typescript                         2.9.2
webpack                            4.20.2
```

### Repro steps
* Open the playground in the browser
* Open a sandboxed component
* Click reload (in the browser)

### Observed Behavior

Sandbox navigates back to a blank page

### Desired Behavior
```
Sandboxed component is reloaded

```

**Comment by timstoddard** [comment]
Hello @jornare,

I am unable to reproduce this bug; I tested in Chrome, Firefox, and Edge. We do not support using Playground in IE.

Does your sandboxed component have routing logic that navigates away from the link for the sandbox, when the page is reloaded? If so, you will need to mock the router in your sandbox to make it a no-op (or at the very least, not actually perform navigation).

Also, try opening the developer console in your browser and going through the repro steps. If there is any error output, please post that here.

**Comment by jornare** [comment]
@timstoddard You're right. I added RouterModule.forRoot([]) in the PlaygroundModule.configure because one of my components had a [routerLink] in it. Adding RouterTestingModule instead worked fine.
