### ISSUE TITLE
SandboxBuilder prepare function

### ISSUE THREAD

**Issue by tfiwm** [SoCreate/angular-playground#158]
Hello,

is there any possibility to prepare data for each sandbox example? Do you have some possible strategies for that?
We are building presenter and smart components. So for presenter components the playground already works amazing!
But for our smart components we would like to mock the states. E.g.: state managements
A prepare function would be really nice to set a state, mock http requests or any kind of code.

If there is at the moment no possibility. What do you think about this idea?

**Comment by tfiwm** [comment]
Yes that's true but what happens if i want to add more examples in the same component sandbox

```typescript
// foo.component.sandbox.ts

class MockService1 {
    getValue() {
        return 'mocked value';
    }
}

export default sandboxOf(AgentFormComponent, {
    declarations: [FooComponent],
    providers: [{ provide: Service1, useClass: MockService1 }]
})
.add('Default', { template: '<app-foo></app-foo>' })
.add('Example 2 with different data from state', { template: '<app-foo></app-foo>' })
```

**Comment by tfiwm** [comment]
What i could imagine is something like in tests:

```typescript
export default sandboxOf(AgentFormComponent, {
    declarations: [FooComponent],
    providers: [{ provide: Service1, useClass: MockService1 }]
})
.add('Default', {
    template: '<app-foo></app-foo>',
    prepare: (httpTestingController: HttpTestingController, store: Store, ...) => {
        // example for http calls
        httpTestingController.expectOne('/data');
        // example ngxs store
        store.reset({})
        // could be anything
    }
})
```

I will try to make this as an experiment and pr for testing ;)
I am happy for any different ideas!

**Comment by timstoddard** [comment]
I would imagine that if you're expecting to get different outputs from a function, that those correspond to some sort of arguments. So, you could expand the mock service I gave earlier to include one or more parameters, and pass in those arguments as `Input()`s to your component. I have updated my previous example to include this sort of functionality; let me know if that solves your issue.

A general rule of thumb that we use at SoCreate is that components that are difficult to mock in tests/sandboxes are probably not using dependency injection efficiently and should therefore be refactored so that they do.

```
// service1.ts

class Service1 {
    getValue(userData: string) {
        switch (userData) {
            case 'foo':
                return 'value 1';
            case 'bar':
                return 'value 2';
            default:
                return 'value 3';
        }
    }
}
```

```
// foo.component.ts

@Component({
    selector: 'app-foo',
    template: '<div>{{ value }}</div>'
})
export class FooComponent implements OnInit {
    @Input() userData: string;
    value = '';

    constructor(private service1: Service1) {}

    ngOnInit() {
        this.value = this.service1.getValue(this.userData);
    }
}
```

```
// foo.component.sandbox.ts

class MockService1 {
    getValue(userData: string) {
        getValue(userData: string) {
        switch (userData) {
            case 'foo':
                return 'mock value 1';
            case 'bar':
                return 'mock value 2';
            default:
                return 'mock value 3';
        }
    }
    }
}

export default sandboxOf(AgentFormComponent, {
    declarations: [FooComponent],
    providers: [{ provide: Service1, useClass: MockService1 }]
})
.add('Default', { template: '<app-foo userData="foo"></app-foo>' });
.add('Example 2 with different data from state', { template: '<app-foo userData="bar"></app-foo>' })
```

**Comment by tfiwm** [comment]
I don't think this will scale good from code perspective. This approach forces me to make my code playground compatible but it should be the opposite.

What is if you want to test an error case of your component as "Example 2". There is no possibility with an argument. Therefor i would just to test if backend request is ok or fails and the reaction of the component -> http mock like in my post as an example.

So the idea is valid but in my opinion it doesn't fit a lot of use cases.
E.g.: with a state management system you just subscribe in your component to some selectors. There is no way with arguments.

**Comment by timstoddard** [comment]
A few things:
- It seems like you're trying to do some sort of testing with Playground. Playground was designed to be able to render a minimal scenario of a component, and we do not support any testing functionality.
- We wrote Playground following the guidelines given in the [Angular Style Guide](https://angular.io/guide/styleguide). So, "Playground compatible" code is simply well-written Angular code, as defined by the official style guide.
- It also seems that you're having issues mocking the ngrx (or a similar) store. I'll include an example of how you could mock that and have different data per scenario.

```
// foo.component.ts

@Component({
    selector: 'app-foo',
    template: '<div>{{ value | async }}</div>'
})
export class FooComponent implements OnInit {
    value: Observable<any>;

    constructor(private store: Store) {}

    ngOnInit() {
        this.value = this.store.select(s => s.data)
    }
}
```

```
// foo.component.sandbox.ts

class MockStore1 {
    select() {
        return Observable.of({ data: 'value1' })
    }
}

class MockStore2 {
    select() {
        return Observable.of({ data: 'value2' })
    }
}

export default sandboxOf(AgentFormComponent, {
    declarations: [FooComponent],
    providers: [{ provide: Service1, useClass: MockService1 }]
})
.add('Default', {
    template: '<app-foo></app-foo>',
    providers: [{ provide: Store, useClass: MockStore1 }]
})
.add('Example 2 with different data from state', {
    template: '<app-foo></app-foo>',
    providers: [{ provide: Store, useClass: MockStore2 }]
});
```

**Comment by tfiwm** [comment]
The idea with the providers self sound like a good way...i haven't saw that this is possible in the `ScenarioConfig`... I will try this!

THX!

**Comment by timstoddard** [comment]
Glad I could help! Have a good day sir :)
