### ISSUE TITLE
Error:  Cannot read property 'parentNode' of undefined  at initializePlayground

### ISSUE THREAD

**Issue by alcfeoh** [SoCreate/angular-playground#162]
### Versions
"angular-playground": "^5.3.0"
    "@angular/animations": "~7.1.0",
    "@angular/cdk": "~7.0.2",
    "@angular/common": "~7.1.0",
    "@angular/compiler": "~7.1.0",
    "@angular/core": "~7.1.0",
    "@angular/forms": "~7.1.0",
    "@angular/http": "~7.1.0",
    "@angular/material": "^7.0.2",
    "@angular/platform-browser": "~7.1.0",
    "@angular/platform-browser-dynamic": "~7.1.0",
    "@angular/pwa": "^0.10.5",
    "@angular/router": "~7.1.0",
    "@angular/service-worker": "~7.1.0",
    "@ngxs/storage-plugin": "^3.3.1",
    "@ngxs/store": "^3.2.0",
    "@okta/okta-signin-widget": "^2.14.0",
    "core-js": "^2.5.4",
    "flexboxgrid": "^6.3.1",
    "hammerjs": "^2.0.8",
    "memo-decorator": "^1.0.2",
    "ngx-logger": "^3.3.6",
    "rxjs": "~6.3.3",
    "zone.js": "~0.8.26"

### Repro steps
Created my playground with the schematics commands, tried to sandbox one component, ran npm run playground, opened my browser to localhost:4201

### Observed Behavior
![image](https://user-images.githubusercontent.com/4699771/53113323-33f7fc80-34f6-11e9-8346-8722fe68fe8e.png)

### Desired Behavior
The sandbox should load properly

**Comment by timstoddard** [comment]
It seems like your selector doesn't match your app root selector. In `main.playground.ts`, make sure the selector is the same as the selector for your app root component.
```
PlaygroundModule
  .configure({
    selector: 'app-root', // (or whatever yours is called)
    ...
  });
```

**Comment by alcfeoh** [comment]
Thanks, that fixed it. Perhaps the schematic could pick the name of that selector automatically rather than assume that it's app-root? Most production applications won't use app-root as a main component selector.
