### ISSUE TITLE
How to inject a Service inside a Sandbox

### ISSUE THREAD

**Issue by bhaidar** [SoCreate/angular-playground#164]
Hi,
Is it possible to inject a Service and call it inside sandbox? I need to use MatDialog service to open dialogs. 

Thanks

**Comment by bhaidar** [comment]
I ended up creating an additional component that actually injects the Service and uses it. Then I sandbox this new component.

**Comment by timstoddard** [comment]
Hey @bhaidar, I'm glad you found a solution to your issue!

Another way to inject services in Playground is to add them as a provider in the config for your sandbox. This saves us from having to create a host component just for the sandboxed scenarios.
```
export default sandboxOf(SomeComponent, {
    imports: [ ... ],
    declarations: [ ... ],
    providers: [MatDialog]
})
.add('Default', {
    template: `
        <app-some-component>
            ...
        </app-some-component>
    `
})
```
In your case, the `MatDialog` service is included in the [`MatDialogModule`](https://github.com/angular/material2/blob/master/src/lib/dialog/dialog-module.ts), so you could alternatively import the whole module if you need other components/providers in that module.
```
export default sandboxOf(SomeComponent, {
    imports: [MatDialogModule],
    declarations: [ ... ],
    providers: [ ... ]
})
.add('Default', {
    template: `
        <app-some-component>
            ...
        </app-some-component>
    `
})
```

**Comment by Tanmay-tfc** [comment]
Could you give some code for calling the service's method in the sandbox component's context?

**Comment by arroyocode** [comment]
Hiya @Tanmay-tfc . Thanks for your interest in Angular Playground. In response to your request, we added some [sandbox service dependency mocking documentation](https://angularplayground.it/docs/how-to/mock-service) earlier today. Hope this helps you.

**Comment by Tanmay-tfc** [comment]
Thanks a lot @arroyocode , this was really helpful. There's one scenario that I needed a little helping with:
I have a modal component that can be opened on-demand by calling the modal service's open method. To check this functionality, I have a button in my sandbox, on-click of which I wanted to open the modal(by calling the service's method).
So do I need create a mockModalService with the actual open method code  and call it on button click? 
Or is 
`export default sandboxOf(MyComponent, {
    providers: [modalService]
})
`
enough to call the actual modalService open menthod in the sandbox

**Comment by arroyocode** [comment]
@Tanmay-tfc As described by @timstoddard above, you can inject your service in your sandbox config. If you need further assistance, we'd appreciate you setting up a github repository demonstrating the issue that we can clone and provide direction/suggestions. Thanks again for your interest in Angular Playground.

**Comment by pascallalonde** [comment]
I think this is also what I am trying to achieve, the sandbox code looks like this:

`
export default sandboxOf(ConfirmPasswordComponent, {
    imports: [CommonsUixModule]
})
    .add('default', {
        template: '<article class="sandbox-component-wrapper"><button mat-raised-button color="primary" (click)="promptForPassword()">Click to confirm</button></article>',
        context: {
            promptForPassword: () => {
                // dialog.open(ConfirmPasswordComponent);
            }
        }
    });
`

The question is how can I access the dialog instance from the context, so I can actually open my component in a dialog?
The ConfirmPasswordComponent requires a MatDialogRef in its constructor so it can be instanciated. So the goal is to be able to open it from the sandbox.

Is there a better way to get this done?
Should I mock a MatDialogRef completely in a provider?

**Comment by pascallalonde** [comment]
Ok, I got it by declaring a wrapper component in the sandbox.

`
@Component({
    selector: 'app-sandbox-component-wrapper',
    template: '<button mat-raised-button color="primary" (click)="promptForPassword()">Click to confirm</button>'
})
class SandboxDialogComponentWrapper {
    constructor(private readonly dialog: MatDialog) {

    }

    promptForPassword(): void {
        this.dialog.open(ConfirmPasswordComponent);
    }
}

export default sandboxOf(SandboxDialogComponentWrapper, {
    imports: [CommonsUixModule],
    declarations: [ConfirmPasswordComponent]
})
    .add('default', {
        template: '<article class="sandbox-component-wrapper"><app-sandbox-component-wrapper></app-sandbox-component-wrapper></article>',
    });
`
