### ISSUE TITLE
What's the resulting output of running --check-errors?

### ISSUE THREAD

**Issue by bhaidar** [SoCreate/angular-playground#167]
Hi,
I am running `npx angular-playground --check-errors`.
At some moment of time, I get the confirmation that `[ng serve]: i ｢wdm｣: Compiled successfully.`

Then, the CLI start outputting lines starting with `Checking ...`

But it never stops! I mean, the command prompt is never free, as if it is stuck somewhere.

What's the typical or proper output of running `npx angular-playground --check-errors`?

**Comment by timstoddard** [comment]
As of the latest version, it should:
* start the angular dev server
* run each sandboxed scenario
* if any sandboxed scenarios have errors, it will print them to the console (default), or write them to an output file (can be configured via the cli or the playground config file)

Note, we fixed a few things regarding the --check-errors functionality in the latest version (5.3.1), so make sure you're using that and not an older version.

Here is the output from running `angular-playground --check-errors` on a repo with a single sandbox file that contains 3 scenarios.
```
angular-playground --config angular-playground.json --check-errors

Successfully compiled sandbox files.
Retrieved 3 scenarios.

Checking [1/3]: ./app/shared/pipes/phone-number/phone-number.pipe.sandbox: Usage
[ng serve]: ** Angular Live Development Server is listening on localhost:7000, open your browser on http://localhost:7000/ **
[ng serve]:

[ng serve]: i ｢wdm｣: wait until bundle finished: /?scenario=.%2Fapp%2Fshared%2Fpipes%2Fphone-number%2Fstyleguide%2Fphone-number.pipe.sandbox/Usage

[ng serve]:
Date: 2019-03-18T22:16:21.091Z
Hash: b8aa4a093a7057a1ada9
Time: 38857ms
chunk {0} 0.js, 0.js.map () 723 kB  [rendered]
chunk {main} main.js, main.js.map (main) 150 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 237 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 8.74 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 158 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.57 MB [initial] [rendered]

[ng serve]: i ｢wdm｣: Compiled successfully.

Checking [2/3]: ./app/shared/pipes/phone-number/phone-number.pipe.sandbox: 10 digit number
Checking [3/3]: ./app/shared/pipes/phone-number/phone-number.pipe.sandbox: 10+ digit number
```

**Comment by bhaidar** [comment]
Thanks @timstoddard for the info! The old version seems was getting stuck somewhere. Now with the upgrade of the package I can see all the scenarios are being checked and running.

Thanks
