### ISSUE TITLE
When running the cli the port is ignored when --check-errors is present.

### ISSUE THREAD

**Issue by ddehghan** [SoCreate/angular-playground#169]
### Versions

> "angular-playground": "5.4.0",

Angular CLI: 7.3.7
Node: 11.7.0
OS: darwin x64
Angular: 7.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.7
@angular-devkit/build-angular     0.13.7
@angular-devkit/build-optimizer   0.13.7
@angular-devkit/build-webpack     0.13.7
@angular-devkit/core              7.3.7
@angular-devkit/schematics        7.3.7
@angular/cdk                      7.3.6
@angular/cli                      7.3.7
@ngtools/webpack                  7.3.7
@schematics/angular               7.3.7
@schematics/update                0.13.7
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
```

### Repro steps
When running the cli the port is ignored when --check-errors is present.


> npx angular-playground

[ng serve]: ** Angular Live Development Server is listening on localhost:7000, open your browser on http://localhost:7000/ **


> npx angular-playground --ng-cli-port 7003  
[ng serve]: ** Angular Live Development Server is listening on localhost:7003, open your browser on http://localhost:7003/ **

when when both the port and check erorrs is set it goes back to 7000

> npx angular-playground --ng-cli-port 7003  --check-errors
[ng serve]: ** Angular Live Development Server is listening on localhost:7000, open your browser on http://localhost:7000/ **


Also can't pass the a config file to specify the port when running --check-errors. It is just not read for some reason. 

> npx angular-playground--config angular-playground-ci.json  --check-errors

angular-playground-ci.json:
{
    "sourceRoot": "./src",
    "angularCli": {
        "appName": "playground",
        "port": 7002
    }
}

### Desired Behavior
```
If you are running multiple builds on the same machine the interfere with eachother when they are all running on port 7000

```

### Any other details that may be useful (optional)

**Comment by timstoddard** [comment]
Hi @ddehghan, thanks for the inquiry about playground!

The error checking utility for playground overrides any port configuration option (if one is given) and instead uses the first free port between 7000 and 9000, so it should not interfere with running playground on other ports - see the link below for the code that does this. If you already have playground running on 7000 and you then run `--check-errors`, the error checker should run on 7001. Also, you don't need to set the port when running `--check-errors` since it will just be overridden.

https://github.com/SoCreate/angular-playground/blob/master/packages/angular-playground/cli/src/run.ts#L23

**Comment by ddehghan** [comment]
Thanks Tim for answering. 

I am not sure that port detection is working correctly. Just run one instance with --check-errors in one tab of osx terminal and run another one in another tab. and you will get:

```
[ng serve]: Port 7000 is already in use. Use '--port' to specify a different port.
[ng serve]: 


[ng serve]: Error: Port 7000 is already in use. Use '--port' to specify a different port.
    at Server.server.once (/Users/user1/gitroot/web-client/node_modules/@angular-devkit/build-angular/src/angular-cli-files/utilities/check-port.js:27:28)
    at Object.onceWrapper (events.js:276:13)
    at Server.emit (events.js:188:13)
    at emitErrorNT (net.js:1281:8)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
[ng serve]: 

```

**Comment by timstoddard** [comment]
Thanks for bringing that to our attention! I have investigated the issue and submitted a PR to fix it. With the next release of Playground, the port error you experienced should no longer happen.

**Comment by ddehghan** [comment]
Oh. Thank you guys. I love the this tool and it is indispensable for a building a large angular app.
