### ISSUE TITLE
After live reload url changes

### ISSUE THREAD

**Issue by therepo90** [SoCreate/angular-playground#175]
### Versions
```
<!--
latest
-->
```

Repro:
open some component sandbox, make code change and wait for code reload, the url gets changed to localhost:4201

**Comment by timstoddard** [comment]
Hi @therepo90, sorry to hear about your issue!

You probably are using `RouterModule` when you should be using `RouterTestingModule`. Please see #151 for details on how to fix. Let me know if that does not solve your issue.

**Comment by therepo90** [comment]
works like a charm, thanks mate :)
thanks for your tool btw
