### ISSUE TITLE
add support for Angular 8

### ISSUE THREAD

**Issue by FDIM** [SoCreate/angular-playground#179]
### Versions
```
"angular-playground": "5.1.3"
```

```
Angular CLI: 8.0.0-rc.4
Node: 10.15.0
OS: win32 x64
Angular: 8.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.4
@angular-devkit/build-angular     0.800.0-rc.4
@angular-devkit/build-optimizer   0.800.0-rc.4
@angular-devkit/build-webpack     0.800.0-rc.4
@angular-devkit/core              8.0.0-rc.4
@angular-devkit/schematics        8.0.0-rc.4
@angular/cdk                      8.0.0-rc.1
@ngtools/webpack                  8.0.0-rc.4
@schematics/angular               8.0.0-rc.4
@schematics/update                0.800.0-rc.4
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
```

### Repro steps

* Step 1 upgrade project to angular 8
* Step 2 npm run playground

### Observed Behavior
```
ERROR in ./node_modules/angular-playground/dist/build/src/shared/sandboxes.js 8:9
Module parse failed: Unexpected token (8:9)
You may need an appropriate loader to handle this file type.
| switch(path) {
| case './common/components/accordion/accordion.component.sandbox':
>   return import( /* webpackMode: "lazy" */ 'C:/...../common/components/accordion/accordion.component.sandbox').then(function(_){ return _.default.serialize('./common/components/accordion/accordion.component.sandbox'); });
| case './common/components/checkbox/checkbox.component.sandbox':
|   return import( /* webpackMode: "lazy" */ 'C:/...../common/components/checkbox/checkbox.component.sandbox').then(function(_){ return _.default.serialize('./common/components/checkbox/checkbox.component.sandbox'); });
```

### Desired Behavior
```
<!-- 
What do you expect to see?
-->
Dev server running
```

### Any other details that may be useful (optional)
As it is now, I had to prefix paths with `!raw-loader!` when importing static html content (old templates)

**Comment by timstoddard** [comment]
Hi @FDIM, thanks for the issue! We're planning to support Angular 8 in Playground once it is released (should be next week according to [Igor](https://twitter.com/IgorMinar/status/1121676911552262145)).

**Comment by EigenTheorist** [comment]
I submitted #183, generally in the same ng8 category but a different error. Do we need to combine?

**Comment by timstoddard** [comment]
@EigenTheorist I think your issue will be solved once we upgrade Playground to v8. We are currently working on upgrading Playground and testing it with our internal applications, so we will put out a v8-compatible release as soon as possible.

**Comment by FDIM** [comment]
Thanks for quick update to angular 8! 

Unfortunately original issue I've reported still persist, but most likely because we use commonjs module type. We still have some old code that relies on `require` and on top of that lodash usage (e.g. `import debounce = require('lodash/debounce');`)

**Comment by timstoddard** [comment]
I see your original comment was using Playground 5.1.3. We are now on 5.7.0 (released yesterday), have you tried with the latest version?

The error you are seeing looks like an issue with the webpack loaders that the ng dev server uses under the hood. I'm not sure what your tsconfig looks like but maybe it's something to do with that? If it helps, we use `"moduleResolution": "node"` and `"target": "es2015"` in our tsconfig for the app we use with playground.

**Comment by FDIM** [comment]
I've tried with 5.6.0, npm did not find 5.7.0 version.

We also have `'module': 'commonjs' ` tsconfig.

Anyway, I'll play around more when I get to work on next week

**Comment by timstoddard** [comment]
I just checked our tsconfig, we use `"module": "esnext"`. If you're still having trouble after you work on the problem some more, feel free to open a new issue as this one is closed.
