### ISSUE TITLE
Host configuration 

### ISSUE THREAD

**Issue by korenb** [SoCreate/angular-playground#181]
Hello!

It would be nice option to add **host** setting to the configuration. It's like `--host={address}` setting in the Angular CLI.

Why? I want to set this setting to `0.0.0.0` to listen all network interfaces over home wi-fi to have ability to connect to sandbox from mobile device.

**Comment by timstoddard** [comment]
Hey @korenb, thanks for the issue! We've decided to add the option you suggested, and will begin work on it soon. As always, feel free to submit a PR for it if you'd like it done sooner.
