### ISSUE TITLE
--check-errors often fails with empty error list

### ISSUE THREAD

**Issue by ddehghan** [SoCreate/angular-playground#182]
Hi guys,

Our CI build often fails with an empty list of errors. We just rerun it and then it succeeds. We attempted to increase the timeout to 180 sec but that does not make a difference.

it does not seems that there is any actual error. And the same code succeeds when we run it again. which component it fails on is also random. 

Any ideas we can try?

Thanks in advance

### Versions
```
        "angular-playground": "5.5.0",
angular ver 7.4
```

### Repro steps
run with: npx angular-playground --check-errors

settings: 
```
{
    "sourceRoot": "./src",
    "timeout": 180,

    "angularCli": {
        "appName": "playground"
    }
}

```

Error message: 
```
...

Checking [44/45]: ./app/viewer/pages/test-page/test-page.sandbox: Test - Test page
Checking [45/45]: ./app/viewer/pages/test-page2/test-page2.component.sandbox: Upload data
Error in the following scenarios
./app/viewer/components/x.component.sandbox
[]
./app/viewer/pages/y.component.sandbox
[]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dm-client@4.0.18 playground-ci: `npx angular-playground --check-errors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dm-client@4.0.18 playground-ci script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by timstoddard** [comment]
Hey @ddehghan, thanks for the issue! We'll look into this soon. As always, if you'd like to submit a PR that fixes this, we'll be happy to help you merge it!

**Comment by ddehghan** [comment]
Thanks for looking at it. 

I think the problem is here: 

https://github.com/SoCreate/angular-playground/blob/74a8727b9966e9e2e3a1df1151e1117201f6ffbd/packages/angular-playground/cli/src/check-errors/verify-sandboxes.ts#L140

My guess is that you are probably capturing some other system events errors and try to add it to the errorReporter and don't succeed and probably then insert nulls in the array. And then later when checking the length to set the process Exit code you are counting those nulls.

**Comment by ddehghan** [comment]
Thank you guys for fixing this.
