### ISSUE TITLE
Cannot run Angular playground in specified port

### ISSUE THREAD

**Issue by seaBubble** [SoCreate/angular-playground#187]
### Versions
```
<!--
5.5.0
-->
```

```
<!--
Angular CLI: 7.3.8
Node: 10.5.0
OS: darwin x64
Angular: 7.2.14
... animations, common, compiler, core, forms, http
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cdk                      7.3.7
@angular/cli                      7.3.8
@angular/compiler-cli             7.2.3
@angular/language-service         7.2.3
@angular/material                 7.3.7
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.5.2
typescript                        3.2.4
webpack                           4.29.0

-->
```

### Repro steps

* ng add angular-playground
* npm run playground
prints
Successfully compiled sandbox files.
[ng serve]: Port 4201 is already in use. Use '--port' to specify a different port.
[ng serve]: 
Error: Port 4201 is already in use. Use '--port' to specify a different port.
    at Server.server.once (<...>/node_modules/@angular-devkit/build-angular/src/angular-cli-files/utilities/check-port.js:27:28)
    at Object.onceWrapper (events.js:273:13)
    at Server.emit (events.js:182:13)
    at emitErrorNT (net.js:1355:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)

* npm run playground --port=4202
prints the same as when I run the command without specifying a port

**Comment by timstoddard** [comment]
Try using the `--ng-cli-port` flag instead of `--port`. We pass that value to the cli's port flag under the hood.

For more info, check out the `angularCli.port` flag on our [config page](https://angularplayground.it/docs/api/configuration).

**Comment by arroyocode** [comment]
@seaBubble Would you mind confirming if @timstoddard 's comment resolved your issue so we can mark this issue closed.

**Comment by arroyocode** [comment]
Hello @seaBubble , we've closed the issue because there has been no response. Thank you for your interest in Angular Playground!
