### ISSUE TITLE
Create a plugin system

### ISSUE THREAD

**Issue by jschwarty** [SoCreate/angular-playground#19]
Initial concept:

Have a way to pass in plugins as `NgModule` classes to the `initializePlayground()` function. Also have a way to pass in `header` and `footer` template strings that could have components from the `NgModule`. This could allow for including rendering custom stuff around the sandboxed components. And these would get applied to each isolated view so you don't need to add it to each `sandboxOf` call.

**Comment by mgmarlow** [comment]
Added in #101
