### ISSUE TITLE
Possibility to use template and styles instead of templateUrl and styleUrls

### ISSUE THREAD

**Issue by wroobell94** [SoCreate/angular-playground#206]
### Versions

angular-playground version ``` 5.2.0 ```

Output from: `ng --version`.

```
Angular CLI: 6.2.9
Node: 10.15.3
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.9
@angular-devkit/build-angular     0.8.9
@angular-devkit/build-optimizer   0.8.9
@angular-devkit/build-webpack     0.8.9
@angular-devkit/core              0.8.9
@angular-devkit/schematics        0.8.9
@angular/cli                      6.2.9
@ngtools/webpack                  6.2.9
@schematics/angular               0.8.9
@schematics/update                0.8.9
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.16.4
```

### Repro steps

I need the playground in a big app. Im yousing both Angular JS ang new Angular in my app. That effects with using ```template``` and ```styles``` instead of ```templateUrl``` and ```styleUrls```. 
The styles and template are imported like 
```
import componentAStyleScss from './coponent-a.component.scss';
```

Is there a possibility to use that with the Playground or maybe override ```@Component``` decorator to pass ```styleUrls``` and ```templateUrl``` to sandboxed component?

### Observed Behavior
```

```

### Desired Behavior
```
possibility to override ```@Component``` decorator or support for ```template``` and ```styles```
```

**Comment by timstoddard** [comment]
Hi @wroobell94, this feature has been requested before (#97) and the SoCreate team does not have any plans to implement it. However, if you would like to submit a PR that adds this functionality, we would be happy to work with you to merge it in.
