### ISSUE TITLE
Should allow extra chromium flags via the config object (e.g. --window-size:800,600)

### ISSUE THREAD

**Issue by vallyian** [SoCreate/angular-playground#210]
https://github.com/SoCreate/angular-playground/blob/119e5817341f5c5f5fba15f9043397e71b1f5407/packages/angular-playground/cli/src/check-snapshots.ts#L41

**Comment by vallyian** [comment]
This is needed for all responsive pges. The extra flags could be either passed on from the CLI, or set in the config, or both.

**Comment by vallyian** [comment]
Form a config point of view, this could also be abstracted out into a "break-points" prop in the config, with "widths" and "heights" arrays and run the regression against all given sizes.

**Comment by grant-wilson** [comment]
This is essential for the visual regressions utility. Further, the snapshots should be compared by size. To expand on what @vallyian is saying, it seems like a key path scenario to want to test your sandbox scenarios against different breakpoints, or simulated device ratios. Bare-bones this would mean providing a width and height config option (and making sure snapshots are compared in kind). Even better would be to have out of the box resolutions based on common devices (like in the device toolbar in Chrome's Developer Tools).

**Comment by timstoddard** [comment]
Hi @vallyian, thanks for the great suggestion! After discussing this, we have decided to move forward with adding this feature. It will be a little while before it gets added, so if you'd like to see this feature added quickly, we're happy to help you merge in a PR from you.
