### ISSUE TITLE
--check-errors and --check-visual-regressions only work with angular-cli

### ISSUE THREAD

**Issue by dgp-web** [SoCreate/angular-playground#215]
### Versions

```
angular-playground version : 6.0.3
```

```
Angular CLI: 8.1.2
Node: 10.13.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.801.2 (cli-only)
@angular-devkit/core         7.3.9
@angular-devkit/schematics   0.8.9
@angular/cdk                 7.3.7
@angular/material            7.3.7
@ngtools/webpack             7.3.9
@schematics/angular          0.8.9
@schematics/update           0.801.2 (cli-only)
rxjs                         6.5.2
typescript                   3.1.6
webpack                      4.39.3

```
### Repro steps
* Step 1: Add angular-playground to NON-cli project as described here https://angularplayground.it/docs/getting-started/non-angular-cli
* Step 2: Run ```angular-playground --check-errors``` or Run ```angular-playground --check-visual-regressions```

### Observed bevahior
```
Please provide Playground's appName in your angular-playground.json file.
```

### Desired Behavior
The awesome testing scripts should be executable even in a non-cli setup.

### Any other details that may be useful (optional)
I am using angular-playground **without angular-cli**.
Building and serving it works perfectly but I cannot leverage the testing scripts since they only work with CLI projects (or I am too stupid to call them correctly which is totally possible).

In the official docs https://angularplayground.it/docs/api/configuration some commands are annotated as being bound to angular-cli. But since --check-errors and --check-visual-regressions are not I was assuming (and hoping) there was a way to use them in a non-cli setup as well.

**Comment by timstoddard** [comment]
Hi @dgp-web, this feature is not on our roadmap so we do not plan to implement it. However, if you would like to submit a PR that fixes this issue, we will be happy to help you merge it into Playground.

**Comment by dgp-web** [comment]
Hi @timstoddard, thanks for answering. I had assumed that it was not possible. 

It would be helpful to indicate on the homepage that @angular/cli is required for the testing features. I was browsing through https://angularplayground.it/docs/api/configuration and the **build** command is annotated with (Requires @angular/cli and @angular/service-worker). These tiny inconsistency caused me to try for some time.

As to your suggestion: if I find the time, I'll be happy to have a look at the scripts and see how they could be adjusted to work without @angular/cli as well.

**Comment by timstoddard** [comment]
Thanks for the suggestion about the docs. I am working on updating the labels for checkErrors and checkVisualRegressions, and the site should be updated shortly.
