### ISSUE TITLE
make visual regression sleep duration configurable

### ISSUE THREAD

**Issue by timstoddard** [SoCreate/angular-playground#222]
### Desired Behavior
Make an option called `visualRegressionSleepDuration` that sets the amount of time to wait after Angular loads the component and all the network requests are idle. Defaults to 100ms.

**Comment by ddehghan** [comment]
Yes. this is very much needed. we sometime get blank screens and I think that is a timing issue. Since we run this regression test offline we can afford giving it much more time to finish to account for the CPU load on the build server.
