### ISSUE TITLE
Build without service-worker?

### ISSUE THREAD

**Issue by guikeller** [SoCreate/angular-playground#224]
Hi guys,

Is it possible to 'build for production' without the use of service-workers?
If so could you please give some more info on how to do that?
I would even be happy with 'debug' JS files.

Our current project does not use service-workers.
We also have no intention of using it at this stage.

Cheers! :+1:

**Comment by guikeller** [comment]
I got it to build for prod using service-workers, but I cannot display any of the sandboxes that I have created. As that is a different issue I should raise a bug, but as this was a timeboxed exercise we won't be going ahead with angular-playground anymore. Closing this issue, cheers.

**Comment by timstoddard** [comment]
Hi @guikeller, I'm sorry to hear that Playground was unable to meet your development needs. I just submitted a PR that makes service workers optional (updated documentation coming soon), so it should work for your case once the PR is merged in if you want to give Playground another shot.

**Comment by guikeller** [comment]
Hi @timstoddard 

I actually could not get the sandbox component to display.
I will raise a bug, so you guys will be able to replicate it.

Cheers
