### ISSUE TITLE
Make Jest dev-dependency? 

### ISSUE THREAD

**Issue by SonyStone** [SoCreate/angular-playground#228]
After update angular-playground it start using `weak-napi`, which using `node-gyp`, which using `Python` which makes Docker unhappy
![image](https://user-images.githubusercontent.com/8790196/69990265-67bc8400-1556-11ea-9398-15de51546483.png)
![image](https://user-images.githubusercontent.com/8790196/69990496-d8fc3700-1556-11ea-87ba-d41bca9aaa93.png)

https://github.com/SoCreate/angular-playground/blob/2183ed244f71d106db76c8a6b67a646b2124ed06/packages/angular-playground/package.json#L67

**Comment by timstoddard** [comment]
Hi @SonyStone, we actually need jest for several of the core features of Playground, so it cannot be moved to the dev deps. You need to install Python in your docker image and then it should work.

**Comment by SonyStone** [comment]
Hi @timstoddard, thanks for quick answer.
Cannot angular-playground use those features directly, without need of jest?
Jest is pretty big dependency for "several" features. What are those features?

**Comment by timstoddard** [comment]
Yes, it is needed for the visual regression features. Many people requested the ability to test their sandbox scenarios for visual regressions, so we do not plan to make it an optional dependency. I know it can be frustrating when dependency authors add/change their dependencies, but that is out of our control as we do not develop Jest.

Are you for some reason unable to install Python on your Docker image?
