### ISSUE TITLE
Unable to use with latest angular cli

### ISSUE THREAD

**Issue by m0t0r** [SoCreate/angular-playground#23]
Hello, 

Thank you for the project, looks very interesting, unfortunately I cannot run playground app with latest `@angular/cli`. 

I am getting the following errors:
```bash
ERROR in /.../demo-app/node_modules/angular-playground/dist/src/app/playground.module.ts (13,36): Cannot find name 'require'.

ERROR in ./~/angular-playground/dist/src/app/playground.module.ts
Module not found: Error: Can't resolve 'sandboxes' in '/Users/..../demo-app/node_modules/angular-playground/dist/src/app'
 @ ./~/angular-playground/dist/src/app/playground.module.ts 18:33-53
 @ ./~/angular-playground/dist/index.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```
I have `angular-playground.json` (/src/angular-playground.json)
```json
{
  "sourceRoot": "./src",
  "angularCli": {
    "appName": "demo-app"
  }
}

```
I created sandboxes folder in `demo-app/src/app/sandboxes` and placed `hello-world.component.sandbox.ts` with

```ts
import { sandboxOf } from 'angular-playground';
import { HelloWorldComponent } from '../../../../src/components/hello-world/hello-world.component';

export default sandboxOf(HelloWorldComponent)
  .add('with default message', {
    template: `<hello-world></hello-world>`
  });
```
but getting the errors above.

Thanks

**Comment by m0t0r** [comment]
I got it working. I had to add `declare var require: any;` to `src/typings.d.ts` as mentioned [here](https://github.com/angular/angular-cli/issues/2221).

**Comment by jschwarty** [comment]
Great! I will work on updating our docs to mention that. 😎
