### ISSUE TITLE
unable to get a production build

### ISSUE THREAD

**Issue by ThomasDeutsch** [SoCreate/angular-playground#24]
when i run „ng build --target production --aot“. 
I will get some errors regarding the template from angular-playgrounds AppComponent.

What am i missing here?

```
ERROR in Template parse errors:
Can't bind to 'ngIf' since it isn't a known property of 'div'. ("
      </symbol>
    </svg>
    <div class="command-bar-shield" [ERROR ->]*ngIf="commandBarActive" (click)="toggleCommandBar()"></div>
    <div class="command-bar" *ngIf="comm"): ng:///xxx/node_modules/angular-playground/dist/src/app/app.component.ts.AppComponent.html@6:36
Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
      </symbol>
    </svg>
```

**Comment by jschwarty** [comment]
So in the `tsconfig.app.json` file you need to exclude `sandboxes.ts`:
```json
"exclude": [
    "sandboxes.ts"
]
````
Might need to exclude `*.sandbox.ts` as well. I will work on getting the docs updated to have this info in there.

Sorry that it took a long time to reply to this. :( I was swamped with ngconf and travel and such.

**Comment by ThomasDeutsch** [comment]
i specified the files  
```js
  "files" : [
    "app/app.module.ts",
    "main.ts"
  ],
```
in the tsconfig.app.json.
now, the production build is working.

Maybe the problem is, that my playground is a separate angular app (specified in angular-cli.json). Because of this, i have two main modules. Only the app module is now referenced in the files section of the tsconfig.app.json.

**Comment by jschwarty** [comment]
Yeah, we have the same cli setup on our app and I sww the same error. I
will try out your setup. Thanks!
