### ISSUE TITLE
xxxx.sandbox.ts is missing from the TypeScript compilation.

### ISSUE THREAD

**Issue by wisespace-io** [SoCreate/angular-playground#240]
### Versions
```
6.2.0
```

```
Angular CLI: 8.3.25
Node: 12.14.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.25
@angular-devkit/build-angular      0.803.25
@angular-devkit/build-ng-packagr   0.803.25
@angular-devkit/build-optimizer    0.803.25
@angular-devkit/build-webpack      0.803.25
@angular-devkit/core               8.3.25
@angular-devkit/schematics         8.3.25
@angular/cli                       8.3.25
@angular/material                  8.2.3
@ngtools/webpack                   8.3.25
@schematics/angular                8.3.25
@schematics/update                 0.803.25
ng-packagr                         5.7.1
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.39.2
```

### Repro steps

* ng add angular-playground
* npm run playground
* add a .sandbox.ts file to the project

### Observed Behavior
notifications.component.sandbox.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (...\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:913:23)
    at \node_modules\@ngtools\webpack\src\loader.js:41:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

### Desired Behavior
```
be able to select the component from the sandbox UI
```

**Comment by andradf** [comment]
While I'm not sure if this was the cause for the original poster, I had the same issue and in the end, after an hour wasted, I figured out that I was running `npm start playground` instead of the correct `npm run playground`. Hope this helps someone else.
