### ISSUE TITLE
How to migrate from 6.x to 7.0 properly?

### ISSUE THREAD

**Issue by ElderOrb** [SoCreate/angular-playground#245]
I've tried to just npm upate  - it didn't download 7.0
Then I tried to change "angular-playground": "^6.2.0" to "angular-playground": "^7.0.0" and then do 'npm update' - but in this case npm run playground fails. 

Any hints?

**Comment by lurock** [comment]
You need to run "ng update angular-playground"

**Comment by ElderOrb** [comment]
Unfortunately the same error: 

```
npx angular-playground                                                                                   Successfully compiled sandbox files.
[ng serve]:
chunk {main} main.js, main.js.map (main) 2.16 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 127 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.02 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 340 kB [initial] [rendered]
Date: 2020-03-09T09:54:36.117Z - Hash: 04c391566f4b893dd77d - Time: 11283ms
[ng serve]:
ERROR in No NgModule metadata found for 'PlaygroundModule'.
```

**Comment by lurock** [comment]
Make sure all your files match the files in the in-depth explanation of the configuration section on this page of the docs.

https://angularplayground.it/docs/getting-started/installation#show-more

Also what version of node, Angular, and Angular CLI are you running?

**Comment by ElderOrb** [comment]
Here is 'ng version' output: 

Angular CLI: 9.0.5                                                                                                                                            Node: 13.10.1                                                                                                                                                 OS: win32 x64                                                                                                                                                                                                                                                                                                               Angular: 9.0.5                                                                                                                                                ... animations, cli, common, compiler, compiler-cli, core, forms                                                                                              ... language-service, platform-browser, platform-browser-dynamic                                                                                              ... router                                                                                                                                                    Ivy Workspace: Yes                                                                                                                                                                                                                                                                                                          Package                           Version                                                                                                                     -----------------------------------------------------------                                                                                                   @angular-devkit/architect         0.900.5                                                                                                                     @angular-devkit/build-angular     0.900.5                                                                                                                     @angular-devkit/build-optimizer   0.900.5                                                                                                                     @angular-devkit/build-webpack     0.900.5                                                                                                                     @angular-devkit/core              9.0.5                                                                                                                       @angular-devkit/schematics        9.0.5                                                                                                                       @angular/cdk                      9.1.1                                                                                                                       @angular/material                 9.1.1                                                                                                                       @ngtools/webpack                  9.0.5                                                                                                                       @schematics/angular               9.0.5                                                                                                                       @schematics/update                0.900.5                                                                                                                     rxjs                              6.5.4                                                                                                                       typescript                        3.7.5                                                                                                                       webpack                           4.41.2


As for the  files in depth - it used to  work with a previous version of playground, although I had to do some manual adjustments to make it compatible with angular 9.x. 

Should I  just remove and install playgrounds?

**Comment by lurock** [comment]
I would remove the manual adjustments and make sure all the files match the files in the in depth configuration. 

You can also try removing the angular-playground package and configuration added by angular playground which is documented in the in-depth configuration.  Then try installing it fresh using "ng add angular-playground".

**Comment by ElderOrb** [comment]
Just tried to remove & install - now it works. But. For some reasons 'ng add angular-playground' didn't change playground version in package.json (I had to do it manually later), although it did regenerate a few .ts files. 

So I  did like this: 
1.) Try 'ng add angular-playground'.
2.) Remove files / entries in angular.json disallowing previous command to succeed
3.) Repeat 1/2 till 1 succeed
4.) Change playground version to  ^7.0.0 in package.json
5.) npm update
6.) Apply my customization-s, like using extra styles/assets to playground build config in angular.json

Now it works!

**Comment by lurock** [comment]
Great!  Glad you were able to get it working.
