### ISSUE TITLE
Is it possible to use HttpClientTestingModule with playgrounds?

### ISSUE THREAD

**Issue by ElderOrb** [SoCreate/angular-playground#247]
I need to make a playground for component which has some httpClient-related code inside, not isolated to service. While I understand that extracting it to service might be much cleaner solution, still curious whether it is possible to mock httpClient itself. 

If possible, can you please share a few lines of code showing how exactly?

**Comment by lurock** [comment]
We have not tried to do that.  We always use services within our components (which is the best practice way of doing it) and mock the services.
