### ISSUE TITLE
feat: Add F1 as supported Key to open Command Bar

### ISSUE THREAD

**Issue by cgatian** [SoCreate/angular-playground#26]
VSCode uses F1 for their Command Pallete, and it's become second nature for me.  CTRL+O works, but wanted to see your thoughts on adding F1 as well.

**Comment by jschwarty** [comment]
Yes, have been thinking about adding key customization. Here are my initial thoughts on implementation:

- Needs to support per user, so if you have Playground in a repo for multiple devs then each dev could somehow override the key settings to match what they want.
- Needs to have a way to have defaults and a way to easily reset to defaults.

I think what I'll do is add F1 (and maybe WebStorm's "find class" command) in as supported command bar toggle stuff, then look at a more robust key binding solution that meets the needs above.

**Comment by jschwarty** [comment]
Added support in [d79adaa](https://github.com/SoCreate/angular-playground/commit/d79adaad7b7924fd80efa705903f0fc5058bb183)
