### ISSUE TITLE
Jest is not in the devDepenendencies

### ISSUE THREAD

**Issue by Halt001** [SoCreate/angular-playground#265]
### Versions

Angular version 10.2
Angular-playground version: 7.1.1

```

```

**Output from: `ng --version:**
Angular CLI: 10.2.0
Node: 14.3.0
OS: darwin x64

Angular: 10.2.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.0
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            10.2.0
@angular-devkit/schematics      10.2.0
@angular/cdk                    10.2.7
@angular/cli                    10.2.0
@schematics/angular             10.2.0
@schematics/update              0.1002.0
rxjs                            6.6.3
typescript                      4.0.5

### Observed Behavior
I see in the source code of version 7.1.1 (you don't seem to have labeled the latest 2 versions) that you have Jest packages under dependencies and not under devDependencies.

    "jest": "^24.9.0",
    "jest-image-snapshot": "^2.12.0",
    "jest-puppeteer": "^4.3.0",

When installing an unrelated package into my workspace I got this warning:

_npm WARN jest-image-snapshot@2.12.0 requires a peer of jest@>=20 <=24 but none is installed. You must install peer dependencies yourself._ 

I found that my jest was too new for this range and it seems only angular playground was dependend on jest-image-snapshot.

**Might it be a mistake that Jest is not in the devDependencies of Angular Playground?**

**Comment by lurock** [comment]
Jest is a dependency because it is used at runtime when running snapshot regression tests.  Please submit a PR if you would like to get it on the latest version of jest and test the snapshot regression tests are still working with the most current version of jest.
