### ISSUE TITLE
ERROR angular-playground.ts(10,25) - Error during template compile of 'PlaygroundModule' [0]  (7.1.1)

### ISSUE THREAD

**Issue by ringodotnl** [SoCreate/angular-playground#266]
Error:
ERROR angular-playground.ts(10,25) - Error during template compile of 'PlaygroundModule' [0]   Function calls are not 
supported in decorators but 'BehaviorSubject' was called.

after running playground

### Versions
"angular-playground": "7.1.1",
"@angular/core": "10.2.0",

Anyone got an idea to fix this ?

====================
Extra info:

Prev. fixed error:
ng serve]: [0] ERROR in The target entry-point "angular-playground" has missing dependencies:

'Fixed' with adding:   
"angularCompilerOptions": {
    "enableIvy": false
  },
to tsconfig.playground.json

Cheers,
Ringo.

**Comment by lurock** [comment]
I have installed the Angular CLI at version 10.2.0 to try to reproduce your issue but did not see a problem.  Here is what I did:

```
npm install -g @angular/cli@10.2.0

ng new angular-test-project

cd angular-test-project

ng add angular-playground

npm run playground
```

**Comment by ringodotnl** [comment]
@lurock cheers, I will try to work my way up to see what causing the issue in our project.
