### ISSUE TITLE
Getting errors after update to Angular 12 and Angular Playground 8.1.0

### ISSUE THREAD

**Issue by DanWahlin** [SoCreate/angular-playground#278]
### Versions
```
8.1.0
```

```
Angular CLI: 12.0.1
Node: 14.16.1
Package Manager: npm 7.12.0
OS: darwin x64

Angular: 12.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@schematics/angular             12.0.1
rxjs                            6.6.7
typescript                      4.2.4
```

### Repro steps
* Clone https://github.com/danwahlin/angular-jumpstart
* npm i
* npm run playground

### Observed Behavior

I updated this project to Angular 12 but I couldn't get Angular Playground to work so I removed the original files in the project since `.angular-playground` is used now days for those (the project has been updated many times over the years). I then re-ran `ng add angular-playground`.

After running `npm run playground`, the bundles build OK but I get a bunch of errors after [ng serve] as shown next:

```
[ng serve]: 
Error: node_modules/angular-playground/dist/schematics/sandbox/files/__name@dasherize__.component.sandbox.ts:2:10 - error TS1003: Identifier expected.

2 import { <%= classify(name) %>Component } from '<%= flat ? '.' : '..' %>/<%= name %>.component';
           ~


Error: node_modules/angular-playground/dist/schematics/sandbox/files/__name@dasherize__.component.sandbox.ts:2:10 - error TS1141: String literal expected.

2 import { <%= classify(name) %>Component } from '<%= flat ? '.' : '..' %>/<%= name %>.component';
           ~


Error: node_modules/angular-playground/dist/schematics/sandbox/files/__name@dasherize__.component.sandbox.ts:2:11 - error TS1110: Type expected.

2 import { <%= classify(name) %>Component } from '<%= flat ? '.' : '..' %>/<%= name %>.component';

// more...
```

### Desired Behavior

Expected playground to load the different scenarios.

### Any other details that may be useful (optional)

To get it to build I had to add `src/` in some paths within the `playground` project in `angular.json` (favicon.ico, assets, styles).

**Comment by lurock** [comment]
I will look into it and get back to you @DanWahlin

**Comment by DanWahlin** [comment]
Thanks! Probably something I'm doing due to the upgrade (a legacy artifact hanging around or something) but I don't know the playground build process well enough to debug those errors.

**Comment by lurock** [comment]
Two fixes to get you going:

In the angular-playground.json file change the sourceRoots property value to './src'.  So it should look like this:

```
{
  "sourceRoots": ["./src"],
  "angularCli": {
    "appName": "playground"
  }
}

```

In the main.playground.ts file change the selector to match your root selector of 'cm-app-component'.  So it should look like this:


```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { PlaygroundModule } from 'angular-playground';
import { SandboxesDefined } from './sandboxes';

platformBrowserDynamic().bootstrapModule(PlaygroundModule
  .configure({
    selector: 'cm-app-component',
    overlay: false,
    modules: [],
    sandboxesDefined: SandboxesDefined
  }))
  .catch(err => console.error(err));
```

**Comment by DanWahlin** [comment]
That fixes it - thanks. When I wiped out the older playground files and re-ran things I forgot about updating the `main.playground.ts` selector (my bad). I would've have thought to update the the `angular-playground.json` file though since it was added via `ng add` so thanks for the info there. Appreciate it!

**Comment by lurock** [comment]
Yeah... the error you were getting because the angular-playground.json did not have the ./src path is a bug and I will be putting a patch out for it so thanks for reporting that issue.

**Comment by DanWahlin** [comment]
Good to know. Thanks again for your help. Appreciate the super quick response.
