### ISSUE TITLE
Example playground not running, not updated to v8.1.1

### ISSUE THREAD

**Issue by randre70** [SoCreate/angular-playground#281]
### Versions
```
8.1.1
```
```
$ ng --version
Angular CLI: 12.0.0
Node: 14.16.1
Package Manager: npm 6.14.12
OS: linux x64
...
```

### Repro steps
* Checkout angular-playground tag v8.1.1
* Run "npm i"
* Run ". scripts/build.sh"
* cd examples/cli-example
* Run "npm run playground"

### Observed Behavior
```
No output
```

### Desired Behavior
```
Playground served
```

### Any other details that may be useful (optional)
See examples/cli-example/src/main.playground.ts
Obviously the example still implements the v7 scheme and hasn't been migrated to v8.1.1

**Comment by lurock** [comment]
Thanks, I have update the example project to work with v8.1.1
