### ISSUE TITLE
HMR With Angular-Playground

### ISSUE THREAD

**Issue by cgatian** [SoCreate/angular-playground#29]
@jschwarty Wanted to get your thoughts on a wiki entry, or perhaps adding to PlaygroundModule.

Recently I migrated over to using this library. One of the downsides to using it was the inability to get HMR working with it. 
One of the most common loaders for adding HMR is [AngularClass/angular2-hmr](https://github.com/AngularClass/angular2-hmr).  This loader requires you to have access to the AppModule to add specific functions that properly wire up the HMR lifecycles. Since the `PlaygroundModule` is owned by the framework, I was unable to add the required functions. 

So, I spent some time researching and created a reusable function to wrap the PlaygroundModule, and provide the required HMR hooks.

https://gist.github.com/cgatian/2e70a3e6721550e70dd9b23f16fa0513

**Usage**:
```
import { hmrBootstrap } from './hmr';

const main = () => {
  return platformBrowserDynamic().bootstrapModule(PlaygroundModule);
};

hmrBootstrap(module, main);
```

**Comment by cgatian** [comment]
I stumbled upon another repo where @jschwarty actually does something very similar to boostrap the HMR, and here I thought I'd pieced together something unique! 😞

**Comment by jschwarty** [comment]
@cgatian Your journey to discovering a solution was unique! And that is just as important :)
