### ISSUE TITLE
Component never resolves items from AsyncPipe

### ISSUE THREAD

**Issue by pascallalonde** [SoCreate/angular-playground#292]
### Versions
```
<!--
angular-playground version
-->
8.2.0
```

```
<!--
Output from: `ng --version`.
-->
12.9.0
```

### Repro steps

* Followed setup instructions
* Generated a sandbox file for my component
* Imported CommonModule in main.playground.ts
* Mocked my service to return an Observable containing an array of items.

### Observed Behavior
```
<!-- Normally this includes a stack trace and some more information -->
```
* Component renders
* Async pipe does not resolve items from Subject.
* Tested with an array instead of an Observable and component renders perfectly

### Desired Behavior
```
<!-- 
What do you expect to see?
-->
```
Items should be resolved from Subject

### Any other details that may be useful (optional)
Can't find anything about AsyncPipe anywhere.

**Comment by lurock** [comment]
We use async pipes in lots of our components and I have not experienced this problem. Did you register the Mock service in the "providers" on the sandbox?
