### ISSUE TITLE
polyfills missing from angular-cli config

### ISSUE THREAD

**Issue by chapati23** [SoCreate/angular-playground#30]
Just tried following your set up guide and stumbled about an error. In the demo `.angular-cli.json` config in the docs you're missing the polyfills http://www.angularplayground.it/docs/getting-started/angular-cli

Needs to have the polyfills:

```
{
...
      "main": "main.playground.ts",
      "polyfills": "polyfills.ts",
...
}
```

**Comment by jschwarty** [comment]
Thanks! Updated the docs site. [87e19ba9](https://github.com/SoCreate/angularplayground.it/commit/87e19ba9b38dd0febc874119488458ddb81fcf4e)

**Comment by chapati23** [comment]
👍
