### ISSUE TITLE
npm module shouldn't include *.ts files

### ISSUE THREAD

**Issue by chapati23** [SoCreate/angular-playground#31]
is including *.ts files in the dist/ necessary for the npm module to function?

because it has some negative side effects:
• `ng lint` will pick up angular-playground files from within node_modules (can be overcome with manually excluding node_modules in `.angular-cli.json`)
• `ng build --aot` will fail due to errors in `node_modules/angular-playground/dist/src/app/app.component.ts.AppComponent.html` (still trying to overcome this one. `"exclude"-section in tsconfig doesn't seem to help…)

**Comment by chapati23** [comment]
i see this is related to https://github.com/SoCreate/angular-playground/issues/24

i also had to specify the "files" array in my tsconfig.app.json to get the --aot builds to work again:

```
  "files": [
    "main.ts",
    "typings.d.ts"
  ],
```

**Comment by jschwarty** [comment]
Ended up needing to deliver the TS files to make it work with one of the releases of the @ngtools with the Angular CLI that was complaining on the AoT precheck run. I would like to not have to deliver those. Just need to get some time to look into that and see if it is still an issue and if there is a way around it.

**Comment by jschwarty** [comment]
Fixed in commit [d64ebf3](https://github.com/SoCreate/angular-playground/commit/d64ebf3842ff9b78dd21ad8f92a880bcfbe1f96b)

Will be available in release 1.7.0
