### ISSUE TITLE
Upgrade to Angular 14 gives ng serve 'Unknown argument: publicHost' error when running playground

### ISSUE THREAD

**Issue by jrdutton** [SoCreate/angular-playground#312]
#### angular-playground version
9.0.1
#### ng version
Angular CLI: 14.0.0
Node: 14.17.3
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 14.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.0
@angular-devkit/build-angular   14.0.0
@angular-devkit/core            13.2.0
@angular-devkit/schematics      13.2.0
@schematics/angular             13.2.3
rxjs                            7.5.5
typescript                      4.7.3
### Observed Behavior
When running angular-playground I see...

Successfully compiled sandbox files.
[ng serve]: Error: Unknown argument: publicHost
[ng serve]:

**Comment by lurock** [comment]
This issue is resolved in latest push of Angular Playground version 10.0.1.

**Comment by jrdutton** [comment]
Thank you so much 🥇
