### ISSUE TITLE
AppComponent section element z-index

### ISSUE THREAD

**Issue by cgatian** [SoCreate/angular-playground#34]
The `section` element is given a z-index of 1.  Is this actually necessary?

 [line of code](https://github.com/SoCreate/angular-playground/blob/efdacb636e020368368af15a7c42e7b5d086a0f9/src/app/app.component.ts#L107)

Reason for removal: Other dev tools such as the [hammerjs-touchemulator](https://github.com/hammerjs/touchemulator) append themselves to the DOM as the last child to the body. Typically element layout would render these elements higher based on DOM order.  Since section has a z-index of 1, any child elements appended to the DOM do not render properly unless given a higher z-index.

Removing the z-index on section doesn't seem to have any negative side effects.

**Comment by jschwarty** [comment]
It's used to keep the command bar above the component render zone.

[line of code](https://github.com/SoCreate/angular-playground/blob/efdacb636e020368368af15a7c42e7b5d086a0f9/src/app/app.component.ts#L23)

So we need to be able to keep that command bar on top of the sandboxed item in some fashion. Maybe a container wrapper around both that wouldn't have a z-index so other things added to DOM won't be affected?

**Comment by cgatian** [comment]
I understand the purpose, I just don't think it's actually necessary. _I think_ 🤔  

I agree the command bar should have a z-index applied, but the section elements should the default z-index of `auto` such that they use the stacking order of the document.

Removing the z-index on the section doesn't seem to have any rendering issues with the command bar.  Is there a specific case I'm missing?

**Comment by jschwarty** [comment]
Gotcha... That one may be okay to remove. I think there is a component in
the example app angular cli that tests that scenario.

**Comment by jschwarty** [comment]
Fixed in PR #36 and will be available in upcoming release 1.7.0
