### ISSUE TITLE
Import css/scss from external files as well as strings in typescript

### ISSUE THREAD

**Issue by oh-wo-dk** [SoCreate/angular-playground#35]
## Idea
* Ability to import css/scss from external files and add them to the `styles?:[string]` parameter of `ScenarioConfig`, e.g. something like:

```typescript
// Would a webpack loader here work? 
import style from "./my-feature.component.sandbox.scss"

import {sandboxOf} from 'angular-playground';
import {MyFeature} from './my-feature.component';

export default sandboxOf(MyFeature, {prependText: 'navigation.'})
  .add('default',
    {
      template: `<my-feature>text for my feature!</my-feature>`,
      styles: [
             // Styles from external file.
            style,
             // Mixed with inline styles
            `
                :host{
                     background-color:red;
                }
            `]
    }
);
```

**Comment by jschwarty** [comment]
Yes, if you leveraged Webpack you could probably accomplish something like what you have here. Similar to how some seed projects leverage `require(templatePath)` to do inline templates. Would probably be something outside of the scope of what Playground is trying to provide as it starts to depend on the implementor's build setup and supporting different cases.
