### ISSUE TITLE
Proxy configs

### ISSUE THREAD

**Issue by kpaxton** [SoCreate/angular-playground#37]
Add in a proxy configuration option. 

Currently when I try to pass in ```--proxy-config proxy.js``` to the ```angularCli.args``` option in the angular-```playground.json``` I get a line in the console saying ```The option '--proxy-config proxy.js' is not registered with the serve command ...```. Our ng serve command in our package.json has exactly the same option passed in and it works.

If I separate the value from the command arg, ```args:["--proxy-config", "proxy.js"]``` it seems to execute, however in this case, since we are using ssl, it throws an error because we are using a ```prompt``` package to allow us to enter the password for our user certificate. ```process.stdin.setRawMode is not a function``` is the error. Not sure if that has something to do with exposing the console to the process or what. 

I'm assuming the ```args``` property expects just boolean arguments. This should be either expanded to accept values or the arguments that expect values should be an option in the ```playground.json``` to take the values.

**Comment by jschwarty** [comment]
What if you try:
```
"angularCli": {
  "args": ["--proxy-config=proxy.js"]
}
```

**Comment by kpaxton** [comment]
@jschwarty I just tried it. Still have the same issue of ```process.stdin.setRawMode is not a function```.

**Comment by mgmarlow** [comment]
Please try the newest version of Playground and open a new ticket if this is still an issue.
