### ISSUE TITLE
Remove Styling from <Section> element

### ISSUE THREAD

**Issue by kpaxton** [SoCreate/angular-playground#38]
The section tag's background-color is set to white which currently overrides our global styles that are imported in the playground.

The only styles that should be applied to the <section> element should only be structural to ensure it takes up the full screen.

**Comment by faroutchris** [comment]
I want to add that the CSS rules for the body and font family also overrides the global styles in my project as well.

**Comment by jschwarty** [comment]
Resolved in version `1.7.1` release.
