### ISSUE TITLE
feat: Make angular-playground compatible with @angular/cli

### ISSUE THREAD

**Issue by beeman** [SoCreate/angular-playground#4]
Just today Angular CLI changed the package name to `@angular/cli` instead of `angular-cli`.

It looks like `angular-playground` makes the assumption that the package `angular-cli` is installed.

https://github.com/SoCreate/angular-playground/blob/9f1a790cfa0499a6cfc7c7088a5cb110da2ce226/src/cli/run-angular-cli.ts#L7

As that package will be deprecated soon, and `angular-playground` just got released, it might make sense to standardize on using `@angular/cli`.

**Comment by jschwarty** [comment]
Thanks for letting us know. I will update the code to support this scenario and publish an update here in a bit.

**Comment by jschwarty** [comment]
Support has been added in version 1.1.6 which has been published and available to npm. See [changelog](https://github.com/SoCreate/angular-playground/blob/master/CHANGELOG.md#116--2017-02-02) for more info.

**Comment by beeman** [comment]
@jschwarty thanks for the quick fix, will test it tonight!
