### ISSUE TITLE
Getting an error when trying to use setTimeout

### ISSUE THREAD

**Issue by m0t0r** [SoCreate/angular-playground#40]
Hi,

I would like to have ability to set timeout for the input data of the component so I can see loading state. When I am trying to use `setTimeout` on `context` I am getting the following error: 

```
ERROR in .../xxx/src/sandboxes/stats-widget.component.sandbox.ts (6,28): Cannot find module 'timers'.
```
I tried to create a mini mock service which uses `setTimeout` and then use it in the `context` but getting the same error.

I am using `angular-playground` with Angular CLI.

**Comment by jschwarty** [comment]
Can you post an example of your `stats-widget.component.sandbox.ts`?

**Comment by m0t0r** [comment]
Hi, @jschwarty, thanks for your reply. It's working fine now, I was doing something wrong.

Will leave a working example here as a reference:

```ts
context: {
      data: (function () {
        return new Promise(resolve => {
          setTimeout(() => resolve({
            value: 3150,
            title: 'Stats 1',
            description: 'Stats description 1'
          }), 1000);
        });
      })()
    },
template: '<app-stats-widget [data]="data | async"></app-stats-widget>'
```
but there is _another problem_. When I switch between sandbox cases using quick search it looks like all cases are already run so I have to refresh page to actually rerun and see the delay I need. Is it possible to run each sandbox case only when you navigate to it and rerun each time you open it again ? I can close this issue and open another one if required.

**Comment by jschwarty** [comment]
@m0t0r You can leave this one open. I will use what you posted to take a look at the issue you are experiencing and get you an answer on that. I might not be able to get to it today but I will get back to you soon on it.

**Comment by m0t0r** [comment]
@jschwarty that's fine, thanks a lot!

**Comment by m0t0r** [comment]
@jschwarty, do you have any updates ?

**Comment by jschwarty** [comment]
It's because you have an IIFE there, and the `*.sandbox.ts` file gets ran as soon as you choose any of the scenarios for that sandboxOf component. So that code is getting run once in that file when the `sandboxOf` function is called.

You could create an accessor so that it is called on execution:
```typescript
context: {
  get data() {
    return new Promise(resolve => {
      setTimeout(() => resolve({
        value: 3150,
        title: 'Stats 1',
        description: 'Stats description 1'
      }), 1000);
    });
  }
}
```

**Comment by m0t0r** [comment]
Yeah, that works fine. Thanks a lot!
