### ISSUE TITLE
help wanted: How to load bootstrap.css into sandboxes

### ISSUE THREAD

**Issue by Hosar** [SoCreate/angular-playground#42]
Hello, thanks for this amazing component. 
How can I load bootstrap.css into sandboxes? I have installed it and added to angular-cli.json but I was unlucky.

The only way I could find, was to add it to the component  styleUrls.

Thanks in advance.

**Comment by mgmarlow** [comment]
@Hosar I was able to bring bootstrap into a sandbox component by adding it to the `styles` section for the playground app within the `angular-cli.json`:

```
    {
      "name": "playground",
      ...
      "styles": [
        "../node_modules/bootstrap/dist/css/bootstrap.min.css"
      ],
      ...
    }
```

**Comment by Hosar** [comment]
@mgmarlow Thanks a lot!

**Comment by Erwol** [comment]
> "styles": [
>         "../node_modules/bootstrap/dist/css/bootstrap.min.css"
>       ],

Side note for `angular-playground@7.1.1`. I had to edit the file `angular-playground.json`, not  `angular-cli.json`. The resulting `json` looks like:

```
{
  "sourceRoots": ["./src"],
  "angularCli": {
    "appName": "playground",
    "styles": [
      "./src/assets/style.css"
    ]
  }
}
```
And it's working like a charm, thanks @Hosar.
