### ISSUE TITLE
Merge efforts with Storybook

### ISSUE THREAD

**Issue by alexborisov** [SoCreate/angular-playground#43]
[Storyboo](https://storybook.js.org) is currently working on support for [Angular 2](https://github.com/storybooks/storybook/tree/269-angular-support). Perhaps you should combine efforts? There are a lot of things todo with playground that are already there in storybook (like plugins).

**Comment by JustinCouto** [comment]
Hey Alex, 

Thanks for reaching out man!  It's much appreciated.  When developing playground, we definitely took inspiration from Storybook.  We think what you guys are doing is great.  For us, playground is an internal tool we use and the goal of the project is to keep it as lightweight as possible.  We think what we are doing is super useful and we wanted to share it with the community.  We plan to continue to keep playground as slim as possible and for that reason it probably won't be a good fit for everyone.  In the cases where it is not, we will totally refer people to Storybook if you have the functionality they are looking for.  It will be great for the community to have multiple options for working on components in isolation.  Everyone working on playground really appreciates the offer to combine forces, but for now we think we want to continue with playground as a standalone project.
