### ISSUE TITLE
Module not found: Error: Can't resolve 'sandboxes' in 'C:\foo\node_modules\angular-playground\dist\src\app'

### ISSUE THREAD

**Issue by elwynelwyn** [SoCreate/angular-playground#5]
Hey, cool project!

I've set this up in my project following your getting started instructions.
It is successfully creating `sandboxes.ts` at `./src/sandboxes.ts`.
However when I try run, I get the following:

```
ERROR in ./~/angular-playground/dist/src/app/load-sandboxes.js
Module not found: Error: Can't resolve 'sandboxes' in 'C:\foo\node_modules\angular-playground\dist\src\app'
 @ ./~/angular-playground/dist/src/app/load-sandboxes.js 2:11-31
 @ ./~/angular-playground/dist/src/app/playground.module.js
 @ ./~/angular-playground/dist/index.js
 @ ./src/main.browser.ts
 @ multi main
```

Here is my `angular-playground.json`:

```
{
  "sourceRoot": "./src"
}
```

It seems as though inside `PlaygroundModule` it tries to provide via `loadSandboxes`, which does `require('sandboxes').default`. What is meant to resolve `sandboxes`? I am using WebPack 2, and tried manually adding an alias to resolve this:

```
resolve: {
        extensions: ['.ts', '.js', '.json'],
        alias: {
            'sandboxes': root('src/app/sandboxes.ts')
        }
    }
```

However this did not work.

I am running version `1.1.7`

Any suggestions?

**Comment by jschwarty** [comment]
Hmm, random guess...maybe the path in the alias (does it need to start with ./src)? I will look into setting up a sample scenario tomorrow and see if I can find an answer.

**Comment by elwynelwyn** [comment]
Sorry, that wasn't super clear. `root()` is a helper function that does a `path.join(__dirname, somePath)`, so I think that path is correct. If I `console.log` it, it has resolved the correct full path, and it's working for other aliases I have setup.

For reference, my environment is based on this repo:
https://github.com/qdouble/angular-webpack2-starter

(alias setup right at the bottom of `webpack.config.ts`, bootstrapping sandbox code in `./src/main.browser.ts`, with a simple demo component created in `./src/app` with a `.sandbox.ts` next to it)

I'm interested to know how `require('sandboxes')` is being resolved in angular-cli builds?

**Comment by jschwarty** [comment]
Got it!
```
'sandboxes': root('src/sandboxes.ts')
```
The `sandboxes.ts` file is in `src` and not `src/app`. Let me know if that works for you. You were on the right track! :)

**Comment by jschwarty** [comment]
We will update the docs site to show how to add the resolve for those using webpack and no Angular CLI. Thanks for inquiring about this @elwynelwyn, will help to lead to better docs! 👍

**Comment by elwynelwyn** [comment]
Doh - thanks!
