### ISSUE TITLE
Installing playground as a project dep (without -g options) does not create the command alias

### ISSUE THREAD

**Issue by tobiaghiraldini** [SoCreate/angular-playground#58]
When I install the library without the global (-g) option:

```
$ npm i -D angular-playground
+ angular-playground@2.2.0

```
I can see that the library is added to node modules, but no angular-playground command is created and linked to the ./node_modules/angular-playground/dist/bin/cli.js

On the other hand, adding the -g option (installing it globally, which maybe is not what you want), the alias gets created

```
$ npm i -D angular-playground -g
/Users/me/.nvm/versions/node/v8.6.0/bin/angular-playground -> /Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/angular-playground/dist/bin/cli.js
```

**Comment by mgmarlow** [comment]
@tobiaghiraldini I'm not sure I'm understanding this issue. When you install the package to your local project there should be no global alias set up for the command. Instead, there is a `node_modules/.bin/angular-playground` entry available for local project use.

**Comment by tobiaghiraldini** [comment]
I see.
There is the command entry in the local node_modules/.bin indeed, but it’s not working in my installation for whatever reasons. Other commands, such as “ng” and others are recognized by the bash.
Maybe is just an overlook on my side, but maybe the docs should say to use the node_modules/.bin/angular-playground command. Or is there anything I can do to make the command to be recognized?

**Comment by mgmarlow** [comment]
Sure, the idiomatic way to handle local CLIs with npm is to add an entry to your `package.json` and call it using npm scripts.

`package.json`:
```
"scripts": {
  ...
  "playground": "angular-playground"
}
```

With the above entry added to your `package.json` you can run it via `npm run playground`. This will use the locally installed instance of whatever package instead of the global.

**Comment by tobiaghiraldini** [comment]
Ahh. That’s great. Thank you for your help. I’ll try to configure it this way and I’ll close the issue eventually!
cheers

**Comment by mgmarlow** [comment]
Sure thing. If you run into any other issues I'd try clearing out your project's `node_modules/` and re-installing. I'll add the process for running the project to the docs.
