### ISSUE TITLE
Sandboxing components from a soft link location

### ISSUE THREAD

**Issue by wake42** [SoCreate/angular-playground#59]
I have a git project that contains a packages directory with different modules that are used to build a component library with ng-packagr and lerna.

Outside of that directory I have an "documentation web" that has a symlink to the directories in packages where the components are. Like this:

```
component-library
|--packages/
|   `--package1/
|    |   `--src/    
|    |       |--component1/
|    |       |    |--xxx.component.ts
|    |       |    |--xxx.component.html
|    |       |    |--xxx.component.sandbox.ts
|    |       |    `-- ...
|    |       |--component2/ ...
|    |       `--package1.module.ts
|    `--package2/ ...
|--doc-web/
     `--src/
         |--app/
         |--symlink to packages/package1/src/
         |--symlink to packages/package2/src/
         `--doc-web components...
```

I'm trying to get Angular playground in the doc-web to recognise the component sandboxes in my packages library, but they are not found.

In doc-web I can get a regular `ng serve` to work if I add the flag `--preserve-symlinks` and I can get the angular playground to stop complaining about not finding the components by adding
```
"angularCli": { args": ["--preserve-symlinks"], ... }
``` 
to the angular-playground.json. However Angular playground still doesn't find any of the sandboxes that are defined in my symlinked directories (if I add sandboxes to components in the doc-web it works just fine).

Is there some limitation that prevents Angular playground from searching after sandboxes in symlinked directories?

I'm using macOS in case that affects something.

**Comment by JustinCouto** [comment]
Hi There, 

Unfortunately, we don't have an easy way to replicate your environment.  The issue probably has something to do with the way symbolic links are followed.  If you are able to figure it out a work-around and would like to submit a pull request, we'd love the help.
