### ISSUE TITLE
Internet explorer problems 

### ISSUE THREAD

**Issue by stckcrsh** [SoCreate/angular-playground#60]
We have been using the playground for a little bit on our macs, but recently we needed to do some testing on internet explorer and while the playground compiles and runs we cant use it because both `ctrl + o` and `F1` are reserved key commands and make it so the app is unusable.

To get this to work we had to go in and change the app to use `F2` instead.

Can you please look into adding atleast one more key command that is usable in Internet Explorer

Thanks,
PS I apologize for this i would never use Internet explorer if it were not for work.

**Comment by JustinCouto** [comment]
Hi There, 

We are a little unclear on what you are doing.  How are you accessing Internet Explorer on your MAC?  Are you doing this by booting into Windows through something like Boot Camp or are you using something like Parallels?

Please help us better understand your issue better.

Thank you!

**Comment by stckcrsh** [comment]
We are using virtualbox to run a windows machine and testing the code there.
The playground runs great but internet explorer uses f1 and ctrl + o as
reserved key commands so we could not get the search bar to open inside the
playground.

We made a workaround of just going in and editing the code to instead use
the f2 key which worked well.

**Comment by JustinCouto** [comment]
Thanks for the info.  We are looking into the possibility to add another shortcut that would work for your issue.  We appreciate your feedback.

**Comment by mgmarlow** [comment]
I have  a PR out to fix this: #62

**Comment by lurock** [comment]
This should be resolved now by changing the shortcut keys to F2 and CTRL+P.
