### ISSUE TITLE
Requirements still say Angular 4.2 or above required

### ISSUE THREAD

**Issue by cjhooker** [SoCreate/angular-playground#63]
Just a minor documentation issue. 

On the Requirements page (http://www.angularplayground.it/docs/getting-started/requirements) it says:

> Requires Angular version 4.2 or above.

but it looks like Playground 2.3.0 now requires Angular version 5.0 or above.

**Comment by mgmarlow** [comment]
Good catch. Thanks for pointing that out.

**Comment by lurock** [comment]
Updated! Thank you.
