### ISSUE TITLE
Not works with monorepo.

### ISSUE THREAD

**Issue by ball6847** [SoCreate/angular-playground#67]
angular-playground only looks for ng bin in node_modules of current working directory.

https://github.com/SoCreate/angular-playground/blob/0d6436a6671997e2e13ae84a7e71f25b6f2f0c10/src/cli/run-angular-cli.ts#L13

On monorepo, with tools like Lerna or yarn workspace, the ng cli could possibly installed on somewhere else, so, looking for ng cli only in current working directory might not be a good deal.

As far as I know, we can use something like `npx` or `yarn` to handle looking up for us (`npx ng serve`, `yarn run ng serve`). But have no idea if this is a standard way that good for most people.

**Comment by JustinCouto** [comment]
Thanks so much for the input.  We are currently working on the V3 release of Playground and are looking into addressing the issues you describe.  We are hoping to release this next version soon, so please stay tuned.

**Comment by mgmarlow** [comment]
Following your suggestion, the Angular CLI path is now exposed as a configuration argument.
```
angular-playground --ng-cli-cmd ./node_modules/@angular/cli/bin/ng
```

[More info](http://www.angularplayground.it/docs/api/configuration)
