### ISSUE TITLE
CLI Schematics

### ISSUE THREAD

**Issue by mgmarlow** [SoCreate/angular-playground#73]
Create a CLI schematics package for Playground to add easier project structuring and templates for sandbox files.

https://github.com/angular/devkit

**Comment by sulco** [comment]
Hey @arroyocode, I'm up to add this: actually I already have a working schematics for adding playground to the workspace (the whole ["Setup with Angular CLI"](http://www.angularplayground.it/docs/getting-started/angular-cli)) and then generating sandbox files, just need to clean things up ;) and of course some guidance as to where would you like to have it within the repo.

Would you care for a contribution? Having just a simple 
```
ng add angular-playground
``` 
would be so cool, and would likely improve the visibility of the project.

**Comment by arroyocode** [comment]
Good day @sulco. We're definitely open to contributions to Playground. Please review our contribution guide (https://github.com/SoCreate/angular-playground/blob/master/CONTRIBUTING.md) first and follow those instructions prior to submitting your PR. We look forward to hearing from you.

**Comment by Buttars** [comment]
I would absolutely love to see this added. This would be a great tool that would save me a lot of time.
