### ISSUE TITLE
 Not working where there is form on template

### ISSUE THREAD

**Issue by purusingh** [SoCreate/angular-playground#91]
### Versions
```
<!--
angular-playground version
-->
```"angular-playground": "^3.4.0"

```

```@angular/cli: 1.2.6
node: 6.9.5
os: win32 x64

### Repro steps
<!--
Simple steps to reproduce this bug.
Please include: commands run, packages added, related code changes.
A link to a sample repo would help too.
-->
* Step 1
Just downloaded the code and ran the application and it works
* Step 2
Changes made to the template  and added from element i.e.

  <form #someForm="ngForm">
</form>
* Step 3
Run the app and open the related component on browser

### Observed Behavior
```

```

### Desired Behavior
```

```it should run and display the page but it gives error

There is no directive with "exportAs" set to "ngForm" ("

### Any other details that may be useful (optional)

**Comment by mgmarlow** [comment]
Can you provide your sandbox file so I can see how you have it set up?

**Comment by purusingh** [comment]
It didn’t work on my example and then I just copied your code and changed on your code from


import { Component, ChangeDetectionStrategy } from '@angular/core';
@Component({
  selector: 'ex-person-bio',
  template: `A big person bio`,
  styles: [`:host { display: block; }`],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class PersonBioComponent {}



To


import { Component, ChangeDetectionStrategy } from '@angular/core';
@Component({
  selector: 'ex-person-bio',
  template:fo `<form #myform=‘ngForm’>A big person </form> `,
  styles: [`:host { display: block; }`],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class PersonBioComponent {}

Sent from my iPhone

On Feb 5, 2018, at 4:55 PM, Graham Marlow <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you provide your sandbox file so I can see how you have it set up?

**Comment by mgmarlow** [comment]
From the sound of it (I can't know for sure until I see your component `sandbox.ts` file) you need to add the import for the Angular form's module.

Something along the lines of:

```
export default sandboxOf(MyComponent, {
  imports: [ FormsModule ]
})
.add('Default', {
  template: `<my-component></my-component>`
});
```

**Comment by purusingh** [comment]
I have imported on app module and playground module. But I will try that also.

Thank you
Puru

Sent from my iPhone

On Feb 5, 2018, at 8:07 PM, Graham Marlow <notifications@github.com<mailto:notifications@github.com>> wrote:


From the sound of it (I can't know for sure until I see your component sandbox.ts file) you need to add the import for the Angular form's module.

Something along the lines of:

export default sandboxOf(MyComponent, {
  imports: [ FormsModule ]
})
.add('Default', {
  template: `<my-component></my-component>`
});

**Comment by mgmarlow** [comment]
I was able to tweak the example project to get it to work with forms like so:

```
// person-bio.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { NgForm } from '@angular/forms';
@Component({
  selector: 'ex-person-bio',
  template: `
    <form #myForm="ngForm" (ngSubmit)="onSubmit(myForm)" novalidate>
      <input name="first" ngModel #first="ngModel">
      <button>Submit</button>
    </form>
  `,
  styles: [`:host { display: block; }`],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class PersonBioComponent {
  onSubmit(f: NgForm) {
    console.log(f.value);
  }
}
```

```
// person-bio.component.sandbox.ts
import {sandboxOf} from 'angular-playground';
import {PersonBioComponent} from './person-bio.component';
import { FormsModule } from '@angular/forms';

export default sandboxOf(PersonBioComponent, {
  imports: [
    FormsModule
  ],
  label: 'feature1'
})
  .add('default', {
    template: `<ex-person-bio></ex-person-bio>`
  });
```

Note that I don't need to add `FormsModule` to `my-playground.module.ts`, since it doesn't need a `forRoot()` call like the `RouterModule` or `AnimationsModule`.

This works when navigating to the "default" scenario for the `PersonBioComponent`. Note that there is an additional sandbox (located in `person-bio.component.other.sandbox.ts`) that will not work, since that sandbox hasn't been updated to include `FormsModule`. So for testing, make sure you navigate to the "default" scenario.

We're currently working on a Tour of Heroes demo to provide a better, complete demonstration of sandboxed components.

If you run into any more issues, feel free to open up a new issue.
