### ISSUE TITLE
Allow for templateUrls and styleUrls pattern to follow Angular Component Metadata

### ISSUE THREAD

**Issue by elmiguel** [SoCreate/angular-playground#97]
Hello! I would like to propose a feature request that I think will help extend the angular-playground feature. 

## Current Template Implementation
```typescript
// ... code
export default sandboxOf(AppComponent, sandboxConfig)
  .add('Label - Hello Message',
    {
      template: `<some-component>{{message}}</some-component>`,
      context: {
        message: Observable.create(obs => obs.next('Hello from Observable!'))
      },
      styles: [<styles_array_here>]
    }
  );
```

### Proposal Feature Functionality
Angular's metadata object allows to point to a `templateUrls` and `styleUrls`. These are picked up by WebPack and by the use of `require` upon the build process.  What is being proposed is that  `ScenarioConfig` also allow for these features.

#### Why for this feature?
More often there is a need to create a demo like feature and that it becomes cumbersome to hardcode the sandbox testing scenarios. The current implementation works great for small snippets of code, but what if there is a need to test something more complex? Copying and pasting the code in the template key slot can muddy up the code creating difficulty to focus on the overall structure of the feature test. 

#### Current Workaround

```typescript
const templateHTML = require('./app.component.html').toString();
const templateCSS = require('./app.component.scss').toString();

export default sandboxOf(AppComponent, sandboxConfig)
  .add('App Component -  Hello Message',
    {
      template: templateHTML,
      context: {
        message: Observable.create(obs => obs.next('Hello from Observable!'))
      },
      styles: [templateCSS]
    }
  );
```  

Now this allows for the current component html to be loaded but this could be any other html file. The same goes for styling and since it is picked up my WebPack, SCSS works for free.

### Addition to the templateUrls and styleUrls feature
Another addition would to be to have Angular Playground look for a sandbox folder in each component main directory:

```
nav/
-- sandbox/
    | -- featureNameOne/
           | -- nav.component.html
           | -- nav.component.scss
           | -- nav.component.ts
           | -- nav.module.ts
           | -- scenario.config.ts
    | -- featureNameTwo/
           | -- nav.component.html
           | -- nav.component.scss
           | -- nav.component.ts
           | -- nav.module.ts
           | -- scenario.config.ts
    | ... more features
-- nav.component.html
-- nav.component.scss
-- nav.component.ts
-- nav.module.ts
-- nav.sandbox.module.ts
```

The `nav.sandbox.module.ts` would be the bootstrapping mechanism for crawling through the sandbox directory and auto labeling via the `featureName` directories | `scenario.config.ts`. This collecting each respective file and adding it to the sandbox via reflection. By adding a `scenario.config.ts` file to each `featureName` directory, this can also allow for pre-configuration for the sandboxed component.

There is also the need to incorporate modules and routing-modules to allow for full complexity testing. A `scenario.config.ts` file would allow the bootstrapping of the `component.module.ts` and the reflect | import into the sandboxed component. 

### Multi-Nested Components, Modules, and Services
When dealing with multi-nested components, modules, services, there could be a need to create a sandbox.manifest.ts file. Instead of creating a sandbox directory, one could also create a manifest file that allow one place to register all the sandbox components, styles, modules, services, etc. This could be export of an `ScenarioConfig` to provide a Sandbox Group Suite. This provides a single place in the main testing component that can provide multiple scenarios.

**Comment by rainboxx** [comment]
Related: #35

**Comment by bjDesign** [comment]
Has this been abandoned?

**Comment by elmiguel** [comment]
I have so busy with work projects I forgot to create a simple project that used the suggested proposal. At the time I believe this was something that was already in the projects future pipeline. I have not used the latest release of this project yet with the latest version of Angular. I see that is now marked as a feature so I would assume that this is now available? If not, can see if I can set some time aside to maybe make a pull request with the implementations needed to make this happen as I if not already a full feature this would a great one to add. Also, with schematics now at the backbone of angular cli, this would be even more flexible then my original proposal.

**Comment by timstoddard** [comment]
The SoCreate team does not plan to implement this feature anytime soon. However, if a member of the community such as yourselves wants to submit a PR that adds this functionality, we would be happy to work with you to merge it in.
